event-catalog/eventcatalog

.changeset/config.json
.changeset/odd-nails-suffer.md
examples/basic/events/AddedItemToCart/examples/example.js
examples/basic/events/AddedItemToCart/index.md
packages/create-eventcatalog/templates/default/events/AddedItemToCart/examples/example.js
packages/create-eventcatalog/templates/default/events/AddedItemToCart/index.md
packages/eventcatalog/components/Mdx/Admonition.tsx
packages/eventcatalog/components/Sidebars/EventSidebar.tsx
packages/eventcatalog/components/Sidebars/ServiceSidebar.tsx
packages/eventcatalog/lib/events.ts
packages/eventcatalog/pages/events/[name].tsx
website/docs/guides/components.md
website/docs/guides/upgrading.md
website/sidebars.js

Fix for #48 and also added missing docs for `upgrading eventcatalog`

fix: now supports any extension for event examples also added missing docs

---

website/docs/guides/events/events-adding-examples.md

Fix typo in page https://eventcatalog.dev/docs/events/adding-examples/ that was preventing me from correctly displaying the code example. The markdown file was referencing UserSignedUp and the example provided was for UserCreated.
Yes.

Fix event typo in adding examples

---

.changeset/purple-islands-cheer.md
packages/eventcatalog/scripts/generate.js

Some code bug checking environment variables when running the generator. The check is now correct.
#84

fix: generator now runs outside of test env

---

.changeset/stale-fans-peel.md
examples/basic/events/AddedItemToCart/index.md
packages/eventcatalog/components/Mermaid/index.tsx
packages/eventcatalog/pages/events/[name].tsx
packages/eventcatalog/pages/services/[name].tsx
website/docs/guides/components.md

Adding more mermaid support in the `<Mermaid />` MDX component.
Using the `charts` prop you can now render any Mermaid information you want.
This allows users to get more from the mermaid library and render any kind of diagram they like in their docs.

feat: adding more mermaid support in mdx

---

.changeset/fair-readers-flash.md
packages/eventcatalog-utils/src/__tests__/utils.spec.ts
packages/eventcatalog-utils/src/events.ts
packages/eventcatalog-utils/src/types.ts
packages/eventcatalog/components/SyntaxHighlighter.tsx
packages/eventcatalog/pages/_app.tsx

Updates to the utils allow users to use `write event` but specify default properties for frontmatter values.
This allows API users to preserve frontmatter properties when creating new events.
An example might be if users have `owners` in their existing catalog files, they can move these onto the new event when it's created.
---
Also added some fixs for max height on schema files and also include font-awesome css file for mermaid diagrams.

feat: allow default frontmatter when creating events

---

.changeset/six-hornets-refuse.md
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/__tests__/assets/aws-mock-responses/client-schemas.ts
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/__tests__/assets/event-markdown-snapshot.ts
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/__tests__/plugin.spec.ts
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/index.ts
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/markdown.ts

AWS EventBridge events without schemas and targets were breaking in the doc generation.
Now it handles events without targets or events.

fix: now renders events without targets or rules

---

.changeset/serious-brooms-try.md
packages/eventcatalog/components/Grids/EventGrid.tsx
packages/eventcatalog/components/Grids/ServiceGrid.tsx
packages/eventcatalog/components/NotFound/index.tsx
packages/eventcatalog/components/Sidebars/ServiceSidebar.tsx
packages/eventcatalog/lib/graphs.ts
packages/eventcatalog/pages/events.tsx
packages/eventcatalog/pages/overview.tsx
packages/eventcatalog/pages/services.tsx

Fix for #100 raised by @otbe.
• Services and Events should render correctly now
• Long names now get truncated on the Graph view and Event/Service pages
• Mermaid diagrams also truncate the names
• Removed the event and service lists on the event page and service page.

fix: issue with long names for services and events rendering incorrectly

---

.changeset/nine-panthers-hide.md
.changeset/wise-carpets-drop.md
packages/eventcatalog/components/Header.tsx
packages/eventcatalog/components/Sidebars/EventSidebar.tsx
packages/eventcatalog/next.config.js
packages/eventcatalog/pages/index.tsx
website/docs/api/eventcatalog.config.js.md

Merging this PR enables the eventcatalog user to specify the basePath of the deployment.
Right now we're able to build a static export and deploy it to `example.com` but its not easy to deploy it to `exmaple.com/my-catalog`.
After the merge you can add `basePath` to your `eventcatalog.config.js` and next will pick it up properly.
I think (!) its safe to assume that every way of building the eventcatalog will result in `eventcatalog.config.js` file being copied next to `next.config.js`. At least thats what I observed during testing this change in this repo and in my local eventcatalog.
yes

Configure base path

---

.changeset/pink-crabs-attend.md
packages/eventcatalog/components/Sidebars/EventSidebar.tsx

The "owners" property on events is optional.
So if the event frontmatter would not have any "owners" defined, you would still see the header & section (see before screenshot). The PR checks if the "owners" are set and if not hides the section.
Before:
After:
yes

feat: Hide owners section if the events has no owners defined

---

.changeset/wise-ducks-knock.md
packages/eventcatalog/tailwind.config.js

Fix for #118
Using tailwind [safelist](https://tailwindcss.com/docs/content-configuration)
Tried using the regex they recommend but it was doubling the CSS output to around 60kb... so using these strings (like in the PR) it keeps the size of the CSS down. This change adds 1kb to the CSS output (30kb total now).

bug: fixed issue with purging css from the admonition component

---

.changeset/dirty-timers-fail.md
packages/eventcatalog-plugin-generator-asyncapi/README.md
packages/eventcatalog-plugin-generator-asyncapi/src/__tests__/plugin.spec.ts
packages/eventcatalog-plugin-generator-asyncapi/src/index.ts
packages/eventcatalog-plugin-generator-asyncapi/src/types.ts
website/docs/api/plugins/plugin-doc-generator-asyncapi.md

Since EventCatalog generates Events based on the AsyncAPI, it is handy to reference the public AsyncAPI documentation on the Event details page as an external link. This will reduce the workload of adding the links manually.
Result:
Yes

feat: asyncapi-plugin Insert external links to the AsyncAPI docs

---

.changeset/gentle-pants-teach.md
packages/eventcatalog/bin/eventcatalog.js

Fix for #131, moving the out directory back to the users directory on build.

fix: build directory is now copied over to the users proejct dir

---

.changeset/olive-windows-pull.md
packages/create-eventcatalog/create-app.ts
packages/create-eventcatalog/templates/default/gitignore

Adding missing types for `node/types` also `out` dir is now ignored in users directory.

fix: adding types for create app and also ignore out dir

---

.changeset/great-lobsters-admire.md
packages/eventcatalog/components/Header.tsx

Header now goes to to the homepage rather than /events page.

fix: header link now goes to landing page

---

.changeset/proud-boats-appear.md
packages/eventcatalog-utils/package.json
packages/eventcatalog-utils/src/__tests__/utils.spec.ts
packages/eventcatalog-utils/src/events.ts

When using `utils` you could specify the frontmatter you want to carry over to new events, this is now merged with data from the new event rather than overriding it every time.

feat: now deepmerge when copying data over from previous frontmatter

---

.changeset/beige-trains-glow.md
packages/eventcatalog/lib/__tests__/graphs.spec.ts
packages/eventcatalog/lib/graphs.ts

Event Catalog generated a nicely looking Mermaid schema of the events/services <> producers/consumers mode.
The name of the events/services was shown with an _ when there were spaces and the nodes were not clickable.
The PR introduces that the name will be displayed, even with spaces AND that the nodes are clickable, navigating them to the event/service page of the node.
Before:
After:
yes

feat: mermaid name and link

---

.changeset/tiny-foxes-mate.md
packages/eventcatalog/pages/events.tsx
packages/eventcatalog/pages/events/[name].tsx
packages/eventcatalog/pages/overview.tsx
packages/eventcatalog/pages/services.tsx
packages/eventcatalog/pages/services/[name].tsx

The page title prefix is currently hardcoded to "EventCatalog", this PR changes the behaviour to use the `title` as prefix like defined in the `eventcatalog.config.js`

bug: use title when setting page title

---

.changeset/cyan-shirts-scream.md
.changeset/dry-cycles-visit.md
packages/eventcatalog-plugin-generator-asyncapi/src/__tests__/assets/valid-asyncapi-2.yml
packages/eventcatalog-plugin-generator-asyncapi/src/__tests__/plugin.spec.ts
packages/eventcatalog-plugin-generator-asyncapi/src/index.ts
packages/eventcatalog-plugin-generator-asyncapi/src/types.ts
website/docs/api/plugins/plugin-doc-generator-asyncapi.md

This small change allows people to specify multiple AsyncAPI files when using the generator.
Implementation for #146 
• `pathToSpec` now accepts string or array.
• When events have been created the producers and consumers are now **merged** which allows the events to grow over multiple files.

feat: now supports multiple asyncapi files

---

.changeset/polite-feet-compare.md
examples/basic/eventcatalog.config.js
packages/eventcatalog-types/src/index.d.ts
packages/eventcatalog/components/Header.tsx
website/docs/api/eventcatalog.config.js.md

The event catalog can be part of a bigger developer portal. It is a common UX that clicking the logo in the top navigation returns the visitor to the homage page of the website. The configuration is optional, If not set the user will navigate to the root of the Event Catalog.
yes

feat: configure homepageLink

---

.changeset/popular-apes-heal.md
packages/eventcatalog/lib/__tests__/graphs.spec.ts
packages/eventcatalog/lib/graphs.ts

When the same events/services are being used in different directions in a diagram, Mermaid considers them the same and renders them as 1 node. This results in graphs like in the screenshot. Not sure if this is desired behaviour?
The PR solves it by making the nodes unique per direction, by adding a little prefix in front of the ID.
Before PR:
After PR: 

fix: mermaid service publish - subscribe

---

.changeset/two-fans-melt.md
examples/basic/events/AddedItemToCart/index.md
examples/basic/events/OrderComplete/index.md
examples/basic/events/OrderConfirmed/index.md
examples/basic/events/OrderRequested/index.md
examples/basic/events/PaymentProcessed/index.md
examples/basic/events/RemovedItemFromCart/index.md
examples/basic/events/ShipmentDelivered/index.md
examples/basic/events/ShipmentDispatched/index.md
examples/basic/events/ShipmentPrepared/index.md
examples/basic/services/Basket Service/index.md
examples/basic/services/Data Lake/index.md
examples/basic/services/Payment Service/index.md
packages/create-eventcatalog/templates/default/events/AddedItemToCart/index.md
packages/create-eventcatalog/templates/default/events/OrderComplete/index.md
packages/create-eventcatalog/templates/default/events/OrderConfirmed/index.md
packages/create-eventcatalog/templates/default/events/OrderRequested/index.md
packages/create-eventcatalog/templates/default/events/PaymentProcessed/index.md
packages/create-eventcatalog/templates/default/events/RemovedItemFromCart/index.md
packages/create-eventcatalog/templates/default/events/ShipmentDelivered/index.md
packages/create-eventcatalog/templates/default/events/ShipmentDispatched/index.md
packages/create-eventcatalog/templates/default/events/ShipmentPrepared/index.md
packages/create-eventcatalog/templates/default/services/Basket Service/index.md
packages/create-eventcatalog/templates/default/services/Data Lake/index.md
packages/create-eventcatalog/templates/default/services/Payment Service/index.md
packages/create-eventcatalog/templates/default/services/Shipping Service/index.md

With the new release of the new `<NodeGraph/>` this PR will move all our examples to use `NodeGraph` vs `Mermaid`.
Mermaid is still there for use, but moving over to NodeGraph as I believe it's a better UX.

chore: update all examples to render node graphs vs mermaid

---

.changeset/khaki-colts-appear.md
packages/eventcatalog/components/Mdx/NodeGraph/GraphElements.ts
packages/eventcatalog/components/Mdx/NodeGraph/__tests__/__snapshots__/GraphElements.spec.ts.snap

The NodeGraph minimum width logic resulted in a too small node.
This PR increased the node width for NodeGraph.
before:
after:
Yes

fix: increase node width for NodeGraph

---

.changeset/large-hairs-wonder.md
packages/eventcatalog/styles/globals.css

Fixes https://github.com/boyney123/eventcatalog/issues/183.
Yes
---
If you're wondering what this piece of code is about:
```css
.d2h-diff-table .d2h-code-side-line {
display: inline-grid;
grid-auto-flow: column;
grid-template-columns: auto 1fr;
grid-gap: 0.6em;
margin-bottom: 0.05em;
padding-right: 4.2em;
}
```
It keeps the position of the `+`/`-` prefix (see line 38 on the right side):
Without it the prefix would be centered to the "line height" (which looks weird if there are a lot of line breaks) (see line 38 on the right side):
---
Other notes:
- Kudos for the project, the Contributing instructions and having a useful default example. Everything is very easy to follow! 👍
- The Contributing instructions mention a `main` branch, but the project actually uses `master`.

fix(logs): break line in diff view

---

.changeset/chatty-laws-attack.md
packages/eventcatalog/scripts/move-schemas-for-download.js

If user removes `events` directory from the catalog they will get an error when the `move-schemas-for-download.js` is run, failing to find the events directory. 
This fix now checks the directory before trying to do anything to it, as the `events` directory is now optional

fix: now check for events dir before moving schemas

---

.changeset/rotten-dots-argue.md
packages/eventcatalog/package.json
packages/eventcatalog/pages/_app.tsx
packages/eventcatalog/pages/_document.tsx
yarn.lock

Updating to new NextJS version and also removing warnings about style sheets and links by moving to new `_document.js` method suggested by NextJs.

chore: update to new nextjs version

---

.changeset/itchy-humans-tickle.md
packages/eventcatalog/components/Grids/EventGrid.tsx

This will fix issues if you have events with the same name but different domain. Without this change you would get weird results in the overview page of events being rendered with filters active that should hide them.
Yes

add a stable render key for events

---

.changeset/olive-dingos-reflect.md
.vscode/settings.json
package.json
packages/eventcatalog-types/src/index.d.ts
packages/eventcatalog-utils/src/types.ts
packages/eventcatalog/components/Mdx/NodeGraph/GraphLayout.ts
packages/eventcatalog/components/Mdx/NodeGraph/NodeGraph.tsx
packages/eventcatalog/components/Mdx/NodeGraph/__tests__/GraphLayout.spec.ts
packages/eventcatalog/package.json
yarn.lock

As [mentioned on discord](https://discord.com/channels/918092420338569216/918092420338569219/948603441528328192) I tried to add a couple of bugfixes which was hindered by current typings.
In this MR I did three things:
1. update TypeScript
2. get rid of `[]` usage in array (e.g. `producerNames?: string[] | Service[] | [];`)
3. introduce union type (for `data: A | B;  source: 'a' | 'b';`)
About **2.**: A type like `string[] | Service[]` already implies that the array can be empty. `const a: string[] | Service[] = []` is completely fine. The type `[]` can actually be worse as it says _you can only be empty_. E.g. mapping over such an collection uses never `empty.map(/** never **/ item => item)`.
About **3*.*: Switching from `data: A | B;  source: 'a' | 'b';` to `{ data: A;  source: 'a'; } | …

improve typings

---

.changeset/serious-beans-study.md
packages/eventcatalog/components/Mdx/NodeGraph/NodeGraph.tsx
packages/eventcatalog/components/Mdx/OpenApiSpec.tsx
packages/eventcatalog/pages/events/[name].tsx

Build no longer worked for EventCatalog due to TypeScript errors and package updates.
Changes
- Fixed how OpenAPI components are imported ([Issue on swagger-ui repo](https://github.com/swagger-api/swagger-ui/issues/7970))
- React flow component changed some types, just ignoring warnings for now, locally not an issue on when building...

fix: build issues with eventcatalog core

---

website/docs/guides/events/events-adding-event.md

Hello there, a very small PR which fixes some typos in events documentation 😉

docs: fixed some typos in events documentation

---

.changeset/tough-crews-count.md
examples/basic/eventcatalog.config.js
packages/eventcatalog-types/src/index.d.ts
packages/eventcatalog/components/Header.tsx
website/docs/api/eventcatalog.config.js.md

Fix for #269
We already have `footerLinks` that allow users to edit footer urls, now users of EventCatalog can now edit header links using EventCatalog.config file.
If no values are provided in the config file, it will default to what it originally has been.

feat - users can now edit header links

---

.changeset/rotten-numbers-scream.md
.changeset/tall-dogs-pretend.md
packages/eventcatalog-plugin-generator-asyncapi/src/__tests__/plugin.spec.ts
packages/eventcatalog-plugin-generator-asyncapi/src/index.ts
packages/eventcatalog-plugin-generator-asyncapi/src/types.ts
packages/eventcatalog-utils/src/__tests__/assets/catalog/domains/My Domain That Already Exists/index.md
packages/eventcatalog-utils/src/__tests__/assets/catalog/domains/Orders/index.md
packages/eventcatalog-utils/src/__tests__/utils.spec.ts
packages/eventcatalog-utils/src/domains.ts
packages/eventcatalog-utils/src/index.ts
packages/eventcatalog-utils/src/markdown-builder.ts
packages/eventcatalog-utils/src/types.ts
website/docs/api/plugins/plugin-doc-generator-asyncapi.md

Eventcatalog does not currently support the interop of AsyncAPI documents into domain boundaries. This functionality is also not supported directly by the AsyncAPI spec and so it makes sense to include the domain boundaries as part of the eventcatalog config rather than trying to develop a new standard for domain boundaries using `x-properties` in the AsyncAPI document. 
To this end, if users would like to break up their AsyncAPI document parsing by domain then each generator in the `generators` field of the `eventcatalog.config.js` file can map to each domain required. If domains are not included then the generator works as before and pushes services and events into the "global" catalog.
A usage example for this would be:
```js
// eventcatalog.config.js
const path = require('path'); …
```

feat(utils/generator-asyncapi): Add domain parsing

---

.changeset/five-cobras-serve.md
examples/basic/eventcatalog.config.js
packages/create-eventcatalog/templates/default/eventcatalog.config.js
packages/eventcatalog-types/src/index.d.ts
packages/eventcatalog/pages/index.tsx
website/docs/api/eventcatalog.config.js.md

#275 , the buttons on the homescreen can now be edited. If you want to remove the `Getting Started` button then you can choose not to pass in the `secondaryCTA` into the config file.

fix - allow button configuration on the homescreen

---

.changeset/breezy-rockets-sip.md
packages/create-eventcatalog/create-app.ts
packages/eventcatalog/package.json
yarn.lock

Small fix, for issues in console when running eventcatalog with autoprefix.
`Replace color-adjust to print-color-adjust`

fix - autoprefix warning in console

---

.changeset/spotty-ducks-tie.md
.changeset/thin-clouds-argue.md
packages/eventcatalog-types/src/index.d.ts
packages/eventcatalog/components/Mdx/AsyncApiSpec.tsx
packages/eventcatalog/lib/__tests__/services.spec.ts
packages/eventcatalog/lib/file-reader.ts
packages/eventcatalog/lib/services.ts
packages/eventcatalog/package.json
packages/eventcatalog/pages/services/[name].tsx
yarn.lock

The possibility of displaying a Swagger UI based on OpenAPI spec files in a Service page is great, however, due to the nature of the API, sometimes it is necessary to write the documentation using a different spec like AsyncAPI.
This feature looks for `async` files in the services folders and uses https://github.com/asyncapi/asyncapi-react to render the documentation in a new MDX component `<AsyncAPI />`.
Attached is an example of an AsyncAPI file displayed in the Service page:
Yes

feat(eventcatalog): rendering of asyncapi files in service page

---

.changeset/loud-tips-sell.md
packages/eventcatalog/components/Mermaid/index.tsx

Hi! The `width` property usage here will break the build as the types are not compatible/expecting these keys. Removing them makes it all work and build as expected.

Mermaid component type error breaks build

---

.changeset/green-cheetahs-develop.md
packages/eventcatalog/pages/_document.tsx

Fix #329
https://app.eventcatalog.dev/overview/ was broken. This should fix it.
Since three@0.145.0 was used directly in _document.tsx, I aligned the use of three@0.145.0/examples/js/renderers/CSS2DRenderer.js.
Yes

fix 3d node graph

---

packages/eventcatalog-utils/src/__tests__/assets/catalog/events/OrderCreated/versioned/0.0.1/index.md
packages/eventcatalog-utils/src/__tests__/utils.spec.ts
packages/eventcatalog-utils/src/events.ts
packages/eventcatalog-utils/src/index.ts
packages/eventcatalog-utils/src/types.ts

I'm using a custom generator plugin to generate events from JSON Schemas, and we have many previous event versions we want to keep documented.
The current `writeEventToCatalog` util can only overwrite an event with a new latest version.
This change makes it easier to write an older version of an event directly.
- update `existsInCatalog` util to optionally look for a versioned event
- update `getEventFromCatalog` util to optionally look for a versioned event
- update `writeEventToCatalog` util to optionally write to a previous version of an event 
Yes

chore(utils): allow writeEventToCatalog to write to previous versions of an event directly

---

.changeset/cyan-ways-kick.md
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/lib/aws.ts

Added a fix for https://github.com/boyney123/eventcatalog/issues/270 so it doesn't fail when it tries to download the schema from a custom registry.
Yes

fix(schemas): Dont fail for schemas in custom registries

---

.changeset/lucky-insects-arrive.md
.changeset/rude-pears-occur.md
packages/eventcatalog/lib/events.ts
packages/eventcatalog/pages/users/[id].tsx

The following PR solves these two problems:
1. when I create a domain without events and add a domain owner, when clicked it does not display returning 404 not found.
2. The user page only returns the information (domains, events and services) that counts available.
yes

fix: correct display of users in domain

---

packages/eventcatalog/tailwind.config.js
website/docs/guides/upgrading.md
website/docusaurus.config.js

After upgrading to **@eventcatalog/core 0.6.8** (following the upgrade guide) to use event tags, our build started to fail because of an outdated **@eventcatalog/types** version. After updating the **@eventcatalog/types** to the latest version in our event catalog project, the build started to work again.
Yes.

docs: add types to upgrade guide

---

.changeset/cuddly-cougars-kick.md
packages/eventcatalog-plugin-generator-asyncapi/src/index.ts

Add path to ParserOptions to resolve relative paths.
Fixes #238.
Yes.

fix: Resolve relative references when parsing AsyncAPI

---

.changeset/short-items-walk.md
packages/eventcatalog/bin/eventcatalog.js

Wanted to check this out and was following the installation guide here https://www.eventcatalog.dev/docs/installation#running-the-development-server. When I tried to `npm run dev`, it failed because there were spaces in my projectDIR path.
Yes

fix: support spaces in projectDIR path

---

.changeset/curvy-pillows-argue.md
packages/eventcatalog/pages/domains.tsx
packages/eventcatalog/pages/events.tsx
packages/eventcatalog/pages/services.tsx

It is difficult to navigate the sidebar filters with too many unsorted events to choose.
This PR sorts them, this is the result:
Yes.

feat: sort sidebar filters

---

.changeset/dull-flies-nail.md
packages/eventcatalog/package.json
yarn.lock

Just locked down the version for now, so we don't get any breaking changes to the app (this happened), we will update the version when we are ready / get more features etc.

chore - locking down Asyncapi version

---

.changeset/khaki-doors-move.md
packages/eventcatalog/components/Mdx/AsyncApiSpec.tsx
packages/eventcatalog/pages/services/[name].tsx
website/docs/guides/components/overview.md
website/docs/guides/components/services.md

Related to #378 and #387. This PR allows the AsyncAPI docs to be fetched from a remote URL by exposing a new AsyncAPI component option (url). Under-the-hood, it uses [FetchingSchemaInterface](https://github.com/asyncapi/asyncapi-react/blob/master/library/src/types.ts#L396) when the url option is specified.
Yes

feat: Allow fetching of remote asyncapi docs

---

.changeset/new-points-wink.md
packages/eventcatalog/pages/overview.tsx

Getting this error on build
```
Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any, string | JSXElementConstructor<any>>'.
Types of property 'key' are incompatible.
Type 'React.Key' is not assignable to type 'import("/Users/dboyne/Dev/OpenSource/eventcatalog-pull-requests/my-catalog/node_modules/@types/react-dom/node_modules/@types/react/index").Key'.
Type 'bigint' is not assignable to type 'Key'.
56 |         nodeThreeObject={(node) => {
57 |           const nodeEl = document.createElement('div');
> 58 |           nodeEl.innerHTML = ReactDOMServer.renderToString(<NodeElement node={node} />);
|
```
This fix, removes the error by a typescript ignore.

fix- build for typescript and react types

---

.changeset/sweet-badgers-obey.md
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/__tests__/assets/event-markdown-snapshot.ts
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/__tests__/plugin.spec.ts
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/index.ts

eventcatalog-plugin-generator-amazon-eventbridge plugin does not populate the frontmatter fields `producers` and `consumers`. The generate command does however always drop these fields even if they had been manually updated. This is confusing behavior. This PR extends the same retain policy that was previously only applied to the `owners` field to also include `producers` and `consumers`.
Tests have been updated to account for the change and all tests pass.
Yes

Eventcatalog plugin generator amazon eventbridge frontmatter config

---

.changeset/old-meals-float.md
packages/create-eventcatalog/create-app.ts

We updated to TypeScript v5 looks like the EventCatalog CLI package was left behind in the migration, this fixes that issue also mentioned in #450

fix: fixing TypeScript version on new catalogs to v5 from v4

---

.changeset/pink-carrots-rush.md
packages/eventcatalog-plugin-generator-amazon-eventbridge/scripts/generate-catalog-with-plugin.js
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/lib/aws.ts
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/types.ts
website/docs/api/plugins/plugin-doc-generator-amazon-eventbridge.md

Hello !
Fix #425
Fix #426
I opened few weeks ago two issues:
- #425: A "bug" that lead the even catalog generator from EventBridge to only retrieve first 100 events
- #426: A feature request to allow use AWS sdk option `SchemaNamePrefix` to filter events
My company as a lot of different events, part because we use a global event bus with all project/environments push on it. So we have:
- More than 100 events schemas
- I am only interested by "production" ones that I can easily filter with the schema name prefix.
That will allow us use the project to document our events.
All changes relate to this AWS SDK function: [listSchemas](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Schemas.html#listSchemas-property)
NB: It is my first contribution to this project and I am not a regular …

Schema discovery upgrade

---

.changeset/great-bulldogs-breathe.md
packages/eventcatalog/bin/eventcatalog.js

When running the build command, the users `eventcatalog.config` file was not copied over, always resulting to the default one. This PR fixes that issue.

fix - copy config file on build

---

.changeset/stale-waves-approve.md
.changeset/witty-years-compare.md
packages/eventcatalog-plugin-generator-asyncapi/package.json
packages/eventcatalog-plugin-generator-asyncapi/src/__tests__/assets/valid-asyncapi-v3-2.yml
packages/eventcatalog-plugin-generator-asyncapi/src/__tests__/assets/valid-asyncapi-v3.yml
packages/eventcatalog-plugin-generator-asyncapi/src/__tests__/plugin.spec.ts
packages/eventcatalog-plugin-generator-asyncapi/src/index.ts
yarn.lock

AsyncAPI have released v3 spec, so this updates the asyncapi plugin to support that.
yes
This is quite large PR, although I don't see how/if I could split it up.
I started working on general v3 support, but found a bug in the process which manifested only with the new `@asyncapi/parser` version and/or the specific case described below. I'm still not exactly sure what causes it, but the code included here fixes that.
The bug only appeared when working with different versions of schemas at the same time - v2 + v3. For some reason the last _version_ parsed would overwrite the previous version's frontmatter. 
E.g. if the list was `[v2, v2, v3]`, then v3 frontmatter would be generated first, but then would be overwritten by any of the v2. Same would happen if it was the other way around - …

feat(asyncapi-generator-plugin): v3 asyncapi schema support + refactor to fix racing condition when writing files

---

.changeset/slow-stingrays-own.md
packages/create-eventcatalog/templates/default/eventcatalog.styles.css
packages/eventcatalog/bin/eventcatalog.js
scripts/start-catalog-locally.js

Fixing files being copied over.

feat - fixing copy over

---

.changeset/cyan-zebras-happen.md
packages/eventcatalog/pages/domains.tsx
packages/eventcatalog/pages/events.tsx
packages/eventcatalog/pages/services.tsx

Implementing suggestion described here (#498)
Changed the input to be a react managed component and checking if the query string "q" is provided.
Can be tested locally calling http://localhost:3000/events/?q=Order and http://localhost:3000/services/?q=Order and http://localhost:3000/domains/?q=Order 
The expected behaviour is that the result list be filtered by the term in the query parameter "q".
Let me know if you have a different suggestion for query parameter.

feat: add search via query parameter for events, services and domains (#498)

---

.changeset/kind-steaks-attack.md
packages/eventcatalog-plugin-generator-amazon-eventbridge/src/lib/aws.ts

Undefined values when rendering SQS as targets in Amazon Event Bridge #501

---

.changeset/little-spies-decide.md
bin/eventcatalog.ts

Fixes #532
EventCatalog build command was not copying over the required files for a build, breaking CI/CD integrations.

fix(core): core folder now copied on buld

---

.changeset/small-lobsters-bake.md
bin/eventcatalog.ts

Adding two new commands `preview` and `start`.
These commands allow users to preview their build directory locally.

feat(core): adding preview and start commands to eventcatalog

---

.changeset/change-ra.md
package-lock.json
package.json

fixes: #541 
I have no idea whether this is a good solution or not.
It seems to fix the problem for me.
If there is a better solution feel free to scrap this :)

fix(core): hydrate content before building

---

.changeset/wet-readers-pump.md
src/components/SideBars/DomainSideBar.astro
src/components/SideBars/ServiceSideBar.astro

feat(core): Renders names for services side bars and also links to services from domains fixed

---

.changeset/cold-drinks-switch.md
src/components/Lists/VersionList.astro

feat(core): versions now show as a dropdown

---

.changeset/serious-sloths-retire.md
examples/default/eventcatalog.config.js
src/components/DocsNavigation.astro
src/utils/config/catalog.ts

Some folks have large sidebars, and also want to hide things. This feature enables folks to hide any resource they like. By default all things are shown.

feat(core): added ability to hide resources in sidebar

---

.changeset/slow-bags-know.md
bin/eventcatalog.ts

Fixed an issue with the start and preview commands, now runs from users catalog.

fix(core): fixed start and preview commands

---

.changeset/fuzzy-seas-report.md
src/layouts/DiscoverLayout.astro

Use domains count, rather than service count when deciding to enable Domains link
Fixes #595

fix: Update Discover nav layout

---

.changeset/brown-wolves-judge.md
astro.config.mjs
bin/eventcatalog.config.ts
examples/default/eventcatalog.config.js
package-lock.json

Our team already runs Docusaurus on port 3000 and we'd like to run the eventcatalog server simultaneously locally. Having a configurable port would be helpful in this case.

feat(config): add port config

---

.changeset/tough-spiders-repair.md
src/components/DocsNavigation.astro
src/layouts/VisualiserLayout.astro

fix(core): fixed typescript issues

---

.changeset/five-terms-try.md
src/components/Seo.astro
src/layouts/CustomDocsPageLayout.astro

When using the default base url configuration it defaults to `/`.
The favicon url is currently evaluated from 
```astro
href={`${import.meta.env.BASE_URL}/favicon.ico`}
```
which results in a url of `//favicon.ico`.
```html
<link rel="icon" type="image/svg+xml" href="//favicon.ico">
```
The browser interprets that as a host and tries to load a favicon from `https://favicon.ico/` (if the catalog url uses https as protocol).
This PR makes the favicon url use the utils method that other places use as well to calculate its url.

fix(core): fixed favicon url

---

.changeset/wicked-cars-hug.md
src/utils/config/catalog.ts

Trying to build eventcatalog without having values for `docs.sidebar.{domains,services,messages,teams,users}` set will result in an error:
```
src/components/DocsNavigation.astro:23:28 - error ts(2352): Conversion of type '{ title: string; trailingSlash: boolean; tagline: string; organizationName: string; homepageLink: string; editUrl: string; logo: { alt: string; src: string; text: string; }; docs: { sidebar: { showPageHeadings: boolean; }; }; }' to type 'CatalogConfig' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
The types of 'docs.sidebar' are incompatible between these types.
23 const eventCatalogConfig = config as CatalogConfig;
~~~~~~~~~~~~~~~~~~~~~~~
Result (95 files): 
- 1 error
``` …

fix(core): sidebar configuration for section visibility is now optional

---

.changeset/three-turkeys-allow.md
astro.config.mjs
bin/eventcatalog.config.ts

feat(core): added optimize flag to make eventcatalog work with large catalogs

---

.changeset/nervous-pets-develop.md
astro.config.mjs
src/components/MDX/SchemaViewer/SchemaViewer.tsx

closes #590
fixes #583
[transformMixedEsModules: true](
https://github.com/event-catalog/eventcatalog/pull/636/files#diff-e0f0c5adbe0b9ca5d0b57caf5cea33a8d88899fd02a43df1e9862b185f8a1e5fR51) fixes the error described in the issue (require not defined). 
Afterwards I encountered "Prism not defined" which can be fixed by importing [prismjs](https://github.com/event-catalog/eventcatalog/pull/636/files#diff-237ec20cf679c8019d1ddb5bd0ea6558e9e361264f6493625762b7a36f338255R3) and is somehow a known problem with astro.
And while the missing CSS was fixed, it still misses some CSS vars to show correct color, border width, background colors and such things and this was fixed by importing the default [theme files](https://github.com/event-catalog/eventcatalog/pull/636/files#diff-237ec20cf679c8019d1d …

fix json schema viewer

---

.changeset/curvy-goats-approve.md
bin/eventcatalog.ts
scripts/build-ci.js
scripts/catalog-to-astro-content-directory.js
scripts/start-catalog-locally.js
scripts/verify-build.js

This PR applies some fixes for cross-compatibility between Operational Systems.
1. Return the use of `cross-env` (used at v1);
2. Change the `glob pattern matcher` behavior for `win32` platform at `scripts/catalog-to-astro-content-directory.js`. Only on `win32`, all `\\` will be replaced with `/`.
Related with [issue#547](https://github.com/event-catalog/eventcatalog/issues/547).
Yes.

fix: cross-compatibility between operational systems

---

.changeset/hungry-ads-wash.md
astro.config.mjs

Fixing https://github.com/event-catalog/eventcatalog/issues/634
Enabling word wrapping by default in the `expressiveCode` being used to render code blocks in md files.
**Before:**
Note the sidebar missing on the right
**After:**
Code block now wraps automatically and sidebar is back.
Yep

fix(core): now word wrapping code blocks by default in markdown files so not to break the layout

---

.changeset/odd-pugs-know.md
src/components/Header.astro

It always adds the leading slash to the logo, avoiding generating a wrong uri in buildUrl when using base.
Resolves #629
yes

fix: enforce the leading slash to the logo

---

.changeset/tender-maps-walk.md
src/components/DocsNavigation.astro
src/pages/docs/[type]/[id]/[version]/index.astro

It removes the forward slash at the anchor element on `DocsNavigationSidebar` preventing double trailing slash when trailingSlash is enabled.
Resolves #638.
Yes.

fix: remove forward slash before # to prevent double trailing slash

---

.changeset/spotty-years-fold.md
src/components/DocsNavigation.astro

This PR resolves #550. It adds `truncate` to the label. The result looks like below:

chore: truncate item label text

---

.changeset/stale-jars-provide.md
src/components/Lists/BasicList.tsx

Added truncate as class to BasicList to also visualise long service/event/domain names correctly on visualiser page.

Fix 697 : Truncate labels on visualiser page

---

.changeset/unlucky-stingrays-work.md
scripts/default-files-for-collections/flows.md
scripts/default-files-for-collections/pages.md

Default for flows are broken in the newest release. This fixes that.

chore(core): fixing default for flows

---

.changeset/orange-goats-yell.md
package-lock.json
package.json
src/utils/__tests__/domains/domains.spec.ts
src/utils/__tests__/domains/mocks.ts
src/utils/__tests__/domains/node-graph.spec.ts
src/utils/collections/util.ts
src/utils/domains/domains.ts
src/utils/domains/node-graph.ts

Includes:
- fix to `domains/getNodesAndEdges`: domain services matches semver or latest.
- fix to `domains/getDomains`: domain services matches semver or latest.
Resolves #714.

fix: semver domains

---

.changeset/few-seas-know.md
bin/eventcatalog.ts

Currently, running the `eventcatalog build` generates the `dist` folder with the `pagefind` index. After, running `eventcatalog dev`, the `.eventcatalog-core` is emptied by by the `copyCore` remnoving the `pagefind` index. 
This PR removes the empty core dir from `copyCore`, keeping the dist folder between commands if needed. 
Resolves #645.

fix: pagefind not found

---

.changeset/large-kangaroos-walk.md
astro.config.mjs

This PR suggests making the home redirect temporary (status 302) rather than permanent (301, used by default).
The default permanent redirect makes it hard to change the `landingPage` config setting since browsers tend to cache 301 redirects, well.. permanently. Any future changes may be ignored by the browser,  leading to unexpected behavior.

Change home redirect status code from permanent to temporary

---

scripts/generate.js

The generator loads the plugins from the eventcatalog.config.js file. This file can be CJS or ESM. 
If its ESM the generator (node) can't work it out as it requires CJS code, but nothing fancy is happening here.
This code fixes that with a temp work around, and also tries to import plugins by checking ESM/CJS compatibility.

fix(core): generate script now works with npm packages

---

.changeset/cuddly-cobras-own.md
src/components/MDX/NodeGraph/NodeGraph.astro
src/components/MDX/NodeGraph/NodeGraph.tsx
src/utils/url-builder-client.ts

As more integrations come on board the eventcatalog.config.js may include node libs (e.g path), that the client cannot use or understand.
In this case the NodeGraph was using the urlBuilder which uses the config file (eventcatalog.config.js) which threw an error as the server side API are not in the browser.
Simple solution for now, was to build a urlBuilder for the client that does not require the config file, but is passed the options instead.
This means any client components build in the future that want a URL building would have to use this. Which I think is OK, for now anyway. We can review in the future.

fix(core): added client side url builder

---

.changeset/smooth-drinks-give.md
src/components/MDX/Flow/Flow.astro
src/components/MDX/NodeGraph/NodeGraph.astro
src/components/MDX/SchemaViewer/SchemaViewer.astro

It replaces the client:load by client:only directive of NodeGraph and SchemaViewer to prevent these from render at build time on the server.
Fix #726

fix: invalid hook call warning

---

.changeset/six-dolphins-protect.md
examples/default/services/OrdersService/openapi.yml
package-lock.json
src/pages/docs/[type]/[id]/[version]/spec/index.astro

having OpenApi spec viewer with a higher level of look and feel to make it readable but operational.

refine and relook rapi-doc openapi renderer

---

.changeset/early-steaks-sparkle.md
examples/default/services/OrdersService/openapi.yml
package-lock.json
src/pages/docs/[type]/[id]/[version]/spec/index.astro

In openApi viewer, the summary was shown in nav bar, and as this became verbose  and hard to read , the option of showing the http verb + endpoint path in navbar seems a better and readable option

add path an verb in openapi viewer nav bar

---

.changeset/wild-lamps-drop.md
scripts/eventcatalog-config-file-utils.js

The old way was giving these errors
```
ROJECT_DIR=/Users/dboyne/dev/eventcatalog/eventcatalog/examples/default node scripts/generate.js
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///Users/dboyne/dev/eventcatalog/eventcatalog/examples/default/package.json" needs an import attribute of type "json"
```
Changed the way the file is now read.

fix(core): fixed issue with importing users package json files

---

.changeset/kind-coins-check.md
scripts/eventcatalog-config-file-utils.js

We were using tmp directories on the OS for a temp `eventcatalog.config.mjs` file, which sounded great!
But when we use the generators, the users files might look like this
```js
import path from "path";
import url from "url";
const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
/** @type {import('@eventcatalog/core/bin/eventcatalog.config').Config} */
export default {
cId: "10b46030-5736-4600-8254-421c3ed56e47",
title: "EventCatalog",
tagline: "Discover, Explore and Document your Event Driven Architectures",
organizationName: "Your Company",
homepageLink: "https://eventcatalog.dev/",
editUrl: "https://github.com/boyney123/eventcatalog-demo/edit/master",
// By default set to false, add true to get urls ending in /
trailingSlash: false,
// Change to make the base url of the …
```

fix(core): fixed issue with using tmp directories

---

.changeset/mighty-lizards-listen.md
package-lock.json
package.json

Fixing 2.9.0, moving rimraf to a dep of the project.

fix(core): moving rimraf to dep of project

---

.changeset/mean-kings-jump.md
examples/default/domains/Orders/services/InventoryService/index.md
examples/default/domains/Orders/services/InventoryService/versioned/0.0.1/index.md
examples/default/domains/Orders/services/NotificationService/index.md
examples/default/domains/Orders/services/OrdersService/index.md
examples/default/domains/Orders/services/OrdersService/versioned/0.0.2/index.md
examples/default/domains/Payment/services/PaymentService/index.md
examples/default/domains/Subscriptions/services/SubscriptionService/index.md
scripts/__tests__/example-catalog/domains/Payment/services/ExternalPaymentService/index.md
scripts/__tests__/example-catalog/domains/Payment/services/ExternalPaymentService/versioned/0.0.1/index.md
scripts/__tests__/example-catalog/services/PaymentService/index.md
scripts/__tests__/example-catalog/services/PaymentService/versioned/0.0.1/index.md
src/components/Lists/RepositoryList.astro
src/components/SideBars/DomainSideBar.astro
src/components/SideBars/MessageSideBar.astro
src/components/SideBars/ServiceSideBar.astro
src/content/config.ts

Added ability to add repo and lang to all resources in EventCatalog.
```
repository:
language: JavaScript
url: https://github.com/event-catalog/pretend-shipping-service
```
Add this to your frontmatter will show in the sidebar
Fix for #897

feat(core): added repo support for all resources

---

.changeset/thin-pens-chew.md
src/components/SideBars/DomainSideBar.astro
src/components/SideBars/MessageSideBar.astro
src/components/SideBars/ServiceSideBar.astro

Clicking a button in a previous version of the changelog would show that changelog, but there is more value just showing the whole changelog of the resource.

fix(core): changelog buttons now render the correct changelog

---

.changeset/fluffy-kids-invent.md
bin/eventcatalog.config.ts
package-lock.json
package.json
src/pages/docs/[type]/[id]/[version]/asyncapi/index.astro

The AsyncAPI renderer in Eventcatalog will render AsyncAPI files, the parser used will parse the schemas for users too.
Normally this is OK, but we are seeing issues when users have avro schemas, and want to keep the schemas as they are.
This optional field let's users render AsyncAPI files without parsing the schemas.

fix(core): new property renderParsedSchemas added

---

.changeset/lovely-hairs-film.md
package-lock.json
src/components/Header.astro

Was taking a look at EC and running on my 27inch 4k Monitor - the catalog header starts to look at bit off as there is a max width set. This PR is now suggesting that we let this flow right to the edges (as the rest of the application does) so everything is in line. See screenshots below:
Before (https://demo.eventcatalog.dev):
After:
Also....
While I was here I noticed that there is a weird z-index issue where the payload content block goes above the header.
Before (https://demo.eventcatalog.dev/docs/events/OrderCancelled/0.0.1): 
After:
What you recon @boyney123 ?

chore(core): fixing z-index issue with the header nav and removing the max-width

---

.changeset/light-meals-play.md
package-lock.json
package.json

It move `@astrojs/check` to devDeps. Astro check is used at build-ci script only.
It move `@types/*` to devDeps as in 95ca9aa the types check was removed.

chore: move types deps to dev deps

---

.changeset/friendly-radios-watch.md
src/eventcatalog.ts

This change allows Astro to resolve the configuration using the astro.config.js with the eventcatalog.config.js and the cli options, ensuring proper handling of the options.
See https://github.com/event-catalog/eventcatalog/issues/1015#issuecomment-2542025240

refactor: remove --root and --port flags from astro preview command

---

.changeset/big-poets-decide.md
.gitignore
examples/default/package.json
package-lock.json
src/__tests__/example-catalog-dependencies/eventcatalog.config.js
src/__tests__/example-catalog-dependencies/package.json
src/__tests__/resolve-catalog-dependencies.spec.ts
src/eventcatalog.config.ts
src/eventcatalog.ts
src/map-catalog-to-astro.js
src/resolve-catalog-dependencies.js

From #930, added the ability to create catalog `dependencies`. These are resources that a team may need for there catalog, but not necessarily own themself.
By specifying a `dependency` EventCatalog will create these resource types for the teams allowing them to use EventCatalog with resources that are external.

feat(core): added ability to specify dependencies for catalogs

---

.changeset/giant-colts-carry.md
eventcatalog/src/utils/collections/util.ts

fix(core): fixed issue with version ordering now uses semver

---

.changeset/sour-mails-mix.md
eventcatalog/astro.config.mjs
eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
examples/default/domains/Orders/services/InventoryService/index.md
examples/default/domains/Orders/services/NotificationService/index.md
examples/default/domains/Orders/services/OrdersService/index.md
examples/default/domains/Payment/services/PaymentService/index.md
examples/default/domains/Subscriptions/services/SubscriptionService/index.md

feat(core) enabled remark-gfm enabling tables in markdown

---

.changeset/eight-badgers-try.md
eventcatalog/src/utils/collections/domains.ts

Fixing matching for the ubiquitous language matching issues #1066
Should now read the filepaths rather than collection names and ids.

fix(core): fixed matching for ubiquitous lang

---

.changeset/ninety-bugs-brake.md
eventcatalog/src/layouts/VerticalSideBarLayout.astro

If an EventCatalog only has messages, then the visualizer does not work. This fixes the default URL that is loaded for the visualizer.

fix(core): visualizer now defaults to correct messages

---

.changeset/grumpy-eels-play.md
eventcatalog/src/utils/__tests__/collections/util.spec.ts
eventcatalog/src/utils/collections/util.ts

Just noticed that the sorted versions list was not returned by the new functionality which causes a wrong order here for example: https://demo.eventcatalog.dev/docs/domains/Orders/0.0.3

Rework how we sort versions

---

.changeset/quote-dependencies-frontmatter.md
src/__tests__/example-catalog-dependencies/eventcatalog.config.js
src/__tests__/resolve-catalog-dependencies.spec.ts
src/resolve-catalog-dependencies.js

Use `gray-matter` to generate dependencies frontmatter, as per discussion in #1081 
Fixes #1081

feat(core): use `gray-matter` to `stringify` dependencies frontmatter

---

.changeset/dirty-sloths-crash.md
eventcatalog/src/components/Tables/Table.tsx
eventcatalog/src/components/Tables/columns/DomainTableColumns.tsx
eventcatalog/src/components/Tables/columns/FlowTableColumns.tsx
eventcatalog/src/components/Tables/columns/MessageTableColumns.tsx
eventcatalog/src/components/Tables/columns/ServiceTableColumns.tsx
eventcatalog/src/components/Tables/columns/SharedColumns.tsx
eventcatalog/src/layouts/DiscoverLayout.astro
eventcatalog/src/pages/discover/[type]/index.astro

Pass only needed props to Table client component to optimize discover page size.
Close #1114

Pass only needed props to Table component to optimize page size

---

.changeset/swift-cheetahs-flow.md
eventcatalog/src/components/Header.astro
eventcatalog/src/layouts/VerticalSideBarLayout.astro
eventcatalog/src/pages/docs/[type]/[id]/[version]/spec/index.astro
eventcatalog/tailwind.config.mjs

- It adjust the spec content page height from 100vh to 100%. 
- It adds header/content as spacing variables to tailwind theme to keep the layout heights consistent across the catalog.
Close #819

Adjust content spec page height to prevent 2 scrolls

---

.changeset/four-trees-mix.md
eventcatalog/src/content/config.ts
eventcatalog/src/pages/docs/[type]/[id]/[version].md.ts
eventcatalog/src/pages/docs/llm/llms-full.txt.ts
eventcatalog/src/pages/docs/llm/llms.txt.ts
eventcatalog/src/pages/docs/teams/[id].md.ts
eventcatalog/src/pages/docs/users/[id].md.ts
examples/default/eventcatalog.config.js
src/eventcatalog.config.ts

This feature enabled https://llmstxt.org/ into EventCatalog
Two new urls are added:
- /docs/llm/llms.txt
- /docs/llm/llms-full.txt
If you enable the feature (through your catalog, off by default) all your markdown is accessible to LLMs for parsing and asking questions etc.
Docs to follow with examples.

feat(core): added support for llms.txt

---

.changeset/thirty-monkeys-suffer.md
eventcatalog/src/components/Tables/columns/ServiceTableColumns.tsx

Fixed an issue with message types in the `sends` column on the Services explore table.
They were either rendering as commands or events, now queries are supported.

fix(core): messages now rendered correctly on service table

---

.changeset/thirty-eagles-chew.md
eventcatalog/src/components/SideNav/TreeView/getTreeView.ts

This PR fixes an issue in `getTreeView` where `basePathname` was previously determined using a hardcoded index (`currentPath.split('/')[1]`). If the URL structure did not conform to expectations (e.g. using `base`), it could lead to incorrect values.
- Updated `basePathname` to dynamically find the first occurrence of `'docs'` or `'visualiser'` in the split path.
- If neither is found, it defaults to `'docs'`.
Fix #1165.

fix: improve `basePathname` selection in `getTreeView`

---

.changeset/brave-seals-clap.md
eventcatalog/src/components/MDX/Tiles/Tile.astro

It add a function to check if the href starts with a protocol (e.g., http, https, ftp). If the href passed is a valid absolute URLs, it is used directly in the anchor element. If not, the `buildUrl` utility is used to create the URL from the passed `href`.
Fix #1201

feat: add protocol check to tile component's href handling

---

.changeset/quick-apricots-clean.md
eventcatalog/src/pages/docs/[type]/[id]/index.astro
eventcatalog/src/pages/visualiser/[type]/[id]/index.astro
eventcatalog/src/utils/url-builder.ts

Links on the new architecture screen ("View in visualizer" and "Read documentation") link to a service/domain without verion. The redirect code was broken as it would duplicate the base path (which would generate an incorrect link)
This PR fixes that issue

fix: Redirects to latest version now work correctly when basePath is used

---

.changeset/rare-hornets-push.md
.changeset/tender-countries-glow.md
eventcatalog/src/components/MDX/Schema.astro

This pull request introduces a new optional `lang` property to the `Props` interface in the `Schema.astro` component.

feat(Schema): add optional language prop for code highlighting

---

.changeset/wild-bees-report.md
eventcatalog/src/components/MDX/Tabs/Tabs.astro

@XaaXaaX found an issue with tabs, this fixes that issue.
In a TabItem has no "title' it will still render the tab heading (default)

fix(core): tabs now support optional title param

---

.changeset/sharp-pillows-press.md
e2e/changelog.spec.ts
eventcatalog/src/utils/collections/changelogs.ts
playwright.config.ts

After updating to Astro's glob loaders, the changelog stopped working as expected, as noted by @Jessewb786 in [this comment](https://github.com/event-catalog/eventcatalog/issues/1200#issuecomment-2733012789).  
This PR fixes the issue by making the necessary adjustments to the changelog logic. Additionally, it adds a simple end-to-end (E2E) test to ensure the behavior remains consistent moving forward.  
_Note: you can check the issue by navigating to https://demo.eventcatalog.dev/docs/services/OrdersService/0.0.3/changelog_

fix: update getCollection filter function to match `changelog.mdx`

---

.changeset/warm-wolves-tan.md
eventcatalog/src/components/SideBars/FlowSideBar.astro
eventcatalog/src/pages/docs/[type]/[id]/[version]/changelog/index.astro
eventcatalog/src/pages/docs/[type]/[id]/[version]/index.astro
eventcatalog/src/types/index.ts
eventcatalog/src/utils/page-loaders/page-data-loader.ts
examples/default/domains/Payment/flows/PaymentProcessed/index.mdx
examples/default/domains/Subscriptions/flows/CancelSubscription/changelog.mdx
examples/default/domains/Subscriptions/flows/CancelSubscription/index.mdx
examples/default/domains/Subscriptions/flows/CancelSubscription/versioned/0.0.1/index.mdx
examples/default/domains/Subscriptions/flows/SubscriptionRenewed/index.mdx

Currently, Flow pages lack a sidebar. It would be helpful to have one that displays previous versions, similar to other resources.
Related issue: https://github.com/event-catalog/eventcatalog/issues/1199
- add FlowSideBar with bare minimum information: versions, owners, RSS, visualizer and changelog buttons
- generate flow changelog page
Additional information can be added later, such as a list of services or messages referenced in the flow.

feat(core): add FlowSidebar; flow changelog

---

.changeset/little-tables-pick.md
eventcatalog/src/components/SideNav/TreeView/getTreeView.ts

- collapses everything except domains in TreeView 
Hey there! I really appreciate you for making such a fantastic tool!
The current implementation of TreeView automatically expands domains, services, and channels (see [getTreeView.ts#L119](https://github.com/event-catalog/eventcatalog/blob/main/eventcatalog/src/components/SideNav/TreeView/getTreeView.ts#L119)). Although this makes sense for domains, it can diminish the user experience when a domain contains a large number of services, as it becomes harder to view and access other components within that domain.
I've chosen the simplest solution for now, but I'm happy to explore other approaches if you're generally open to the idea.
Alternative solutions:
- only auto-collapse if there are more than X services
- make the list …

feat(core): collapse everything except domains in TreeView

---

.changeset/smart-grapes-develop.md
eventcatalog/src/components/Lists/CustomSideBarSectionList.astro
eventcatalog/src/components/MDX/ResourceGroupTable/ResourceGroupTable.astro
eventcatalog/src/components/MDX/ResourceGroupTable/ResourceGroupTable.client.tsx
eventcatalog/src/components/MDX/components.tsx
eventcatalog/src/components/SideBars/DomainSideBar.astro
eventcatalog/src/components/SideBars/FlowSideBar.astro
eventcatalog/src/components/SideBars/MessageSideBar.astro
eventcatalog/src/components/SideBars/ServiceSideBar.astro
eventcatalog/src/components/Tables/columns/ServiceTableColumns.tsx
eventcatalog/src/components/Tables/columns/TeamsTableColumns.tsx
eventcatalog/src/content.config.ts
eventcatalog/src/utils/collections/icons.ts
eventcatalog/src/utils/collections/services.ts
examples/default/domains/Orders/index.mdx

Added new `resourceGroups` property to all resources in EventCatalog.
The ability to link any resource with any resource in eventcatalog. This comes with two new things a custom sidebar and also new table to show on your pages.
This new functionality was added to give people flexibility to connect resources together. An example would be to have a domain list a group of messages together, or cross domain services. You can put them into there own resource, and have EventCatalog render these.
A few folks have asked about ways to customize how there resources are connected be it in there DDD environment or the way they handle domains/services and messages. This lets people explore new patterns, and governance patterns, whilst keep the models the same.
Docs, pics and examples coming.

feat(core): added resource groups

---

.changeset/happy-parents-drop.md
eventcatalog/src/components/Lists/PillListFlat.tsx

When a resource name is too long, it makes the icon shrink. 
Before:
After:
> [!WARNING]
> Please let me know if this isn't the right way to fix the issue. I'm not a web developer 😅

fix(core): prevent icon shrinking in PillListFlat.tsx

---

.changeset/fair-plums-march.md
eventcatalog/src/components/MDX/ResourceLink/ResourceLink.astro

- (fix) Avoid trailing and leading whitespaces. Trailing underline appears when text is placed directly after the component.
```
<ResourceLink type="domain" id="Orders">Orders</ResourceLink> test
```
- (fix|improvement) When no version is specified, point to the latest version instead of `/docs/${collection}/${id}`. 
- The redirect pages are not generated for flows and queries ([source](https://github.com/event-catalog/eventcatalog/blob/main/eventcatalog/src/pages/docs/%5Btype%5D/%5Bid%5D/index.astro#L34)). The current implementation just points to a non existing page. 
- This also avoids the needless intermediate redirect 
- (improvement) Fallback to resource name if no slot content provided.  I’d assume in most cases users will want to use the name, not custom text. By the way, the …

feat(core): fixes and improvements for ResourceLink

---

.changeset/sweet-carrots-lie.md
eventcatalog/src/pages/docs/[type]/[id]/[version]/changelog/index.astro

Changelog pages don't pass MDX components, leading to missing import errors, as noted in #1339.
- Closes #1339

fix: add missing mdx components to changelog pages

---

.changeset/calm-nails-knock.md
eventcatalog/src/content.config.ts

Looks like #1340 introduced some issues with catalogs #1349
reverting the change (For now)

fix(core): revert for 1340

---

.changeset/afraid-lizards-draw.md
eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx

- add colors for missing types in NodeGraph legend
- use the midpoint color of the node gradient for easier association

fix(core): add colors for missing types in NodeGraph legend

---

.changeset/flat-days-smile.md
eventcatalog/src/pages/docs/[type]/[id]/[version]/changelog/index.astro

When rendering changelog pages, the version list includes versions from all items in the collection, rather than only the item the changelog is being generated for. This causes the previous version to be calculated incorrectly, resulting in a missing diff between the current and the actual previous version.
For example:
- the resource for which the changelog is being generated has versions 2.0.0 and 1.0.0.
- there is another resource in the same collection with version 1.5.0.
In this case, the system incorrectly identifies 1.5.0 as the previous version instead of 1.0.0, resulting in the diff being calculated between 2.0.0 and 1.5.0.

fix(core): fix versions list in changelog

---

.changeset/small-bees-shake.md
eventcatalog/src/components/MDX/NodeGraph/Nodes/Channel.tsx
eventcatalog/src/components/MDX/NodeGraph/Nodes/Command.tsx
eventcatalog/src/components/MDX/NodeGraph/Nodes/Custom.tsx
eventcatalog/src/components/MDX/NodeGraph/Nodes/Event.tsx
eventcatalog/src/components/MDX/NodeGraph/Nodes/Query.tsx
eventcatalog/src/components/MDX/NodeGraph/Nodes/Service.tsx
eventcatalog/src/components/MDX/NodeGraph/Nodes/User.tsx

As of now, the node label is used only in the full mode. This PR add is to the simple mode.

fix(core): use the node label in simple mode too

---

.changeset/cool-insects-approve.md
eventcatalog/src/pages/docs/teams/[id]/index.astro
eventcatalog/src/pages/docs/users/[id]/index.astro

- use the same CSS classes for layout as in `docs/[type]/[id]/[version]/index.astro`
- add "stats" table to Team page, similar to one on User page
- replace messages (events and commands) + queries in team sidebar with just messages (events, commands, queries)
The layout on the User and Group pages are not consistent with the rest of the pages.
Documentation page used as a reference:
Team page before and after:
User page before and after:

fix(core): consistent layout on User and Team pages

---

.changeset/mean-lemons-rescue.md
eventcatalog/src/components/Lists/ProtocolList.tsx
eventcatalog/src/components/SideBars/ChannelSideBar.astro
eventcatalog/src/components/SideBars/DomainSideBar.astro
eventcatalog/src/components/SideBars/FlowSideBar.astro
eventcatalog/src/components/SideBars/MessageSideBar.astro
eventcatalog/src/components/SideBars/ServiceSideBar.astro

A small change to make style of sidebar labels consistent.
-  There is no need to have resource type in the label. If we are on a Service page, it is obvious that Owners stands for service owners. What we have right now:
- ServiceSidebar: `Versions` but `Service Owners`
- DomainSidebar: `Services` and `Versions` but `Domain Owners`
- MessageSidebar: `QueryVersions`, `Query Owners`, ...
- etc... 
- Make RSS and Channel protocols semibold to match other labels

fix(core): style of sidebar labels

---

.changeset/unlucky-numbers-invent.md
src/eventcatalog.ts

Our gitlab pipelines showed as successful even though the eventcatalog build failed. The problem lies with the unix command executed with `execSync`. It's a small fix, just adding `bash -c "set -o pipefail;`

fix(core): propagate vite error in eventcatalog build correctly

---

.changeset/clever-moles-promise.md
src/analytics/log-build.js
src/eventcatalog.ts

When running `generate` it now reads/parses your `.env` file.

Reading env file for generate script

---

.changeset/silly-cycles-buy.md
eventcatalog/src/layouts/VerticalSideBarLayout.astro
src/catalog-to-astro-content-directory.js

EventCatalog will now load the `eventcatalog.styles.css` style sheet.

fix(core): now loads the eventcatalog stylesheet

---

.changeset/four-games-juggle.md
eventcatalog/src/pages/docs/[type]/[id]/[version]/index.astro
eventcatalog/src/utils/collections/util.ts
examples/default/domains/E-Commerce/index.mdx

Added ability to embed more than one node graph in docs.
Example
```
<div class="grid grid-cols-2 gap-4 not-prose">
<NodeGraph id="Orders" version="0.0.3" type="domain" />
<NodeGraph id="Subscription" version="0.0.1" type="domain" />
</div>
```

feat(core): added ability to embed any nodegraph in your docs

---

.changeset/late-points-laugh.md
eventcatalog/src/utils/protocols.tsx

The protocol icon caused graphe being empty , giving following error in browser console 
The issue is happening only if a channel does not provide protocols property in markdown

fix(core): fix protocol icon nullability issue

---

.changeset/thin-penguins-drive.md
eventcatalog/src/components/MDX/NodeGraph/NodeGraph.astro
eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx

Version dropdown (top right) added to the visualizer. If a resource has multiple versions you can now swap between them.

feat(core): version dropdown added to visualizer

---

.changeset/dull-beers-juggle.md
eventcatalog/src/components/SideNav/ListViewSideBar/utils.ts
eventcatalog/src/content.config.ts
eventcatalog/src/layouts/VerticalSideBarLayout.astro
eventcatalog/src/pages/visualiser/[type]/[id]/[version]/index.astro
eventcatalog/src/pages/visualiser/[type]/[id]/index.astro

Fix for #1047
Added new property to all resources
```
visualiser: false/true
```
Setting the value to false will no longer render the page in the visualizer.

feat(core): added ability to turn of visualizer per resource

---

.changeset/healthy-carpets-grab.md
eventcatalog/src/content.config.ts

Deprecated fields for resources (dates) can now be dates or strings.

fix(core): deprecated dates can now be strings

---

.changeset/grumpy-experts-wave.md
eventcatalog/src/components/MDX/SchemaViewer/SchemaViewer.astro

Attempts to fix https://github.com/event-catalog/eventcatalog/issues/1448
It looks like that when the `SchemaViewer` component was processing the schema being passed in, it was not taking into account the refs property and loading the associated definitions.
This PR adds support for refs when processing schemas now in the `SchemaViewer` component.
```
{
"$ref": "#/definitions/exampleSchema",
"definitions": {
"exampleSchema": {
"type": "object",
"properties": {
"employeeNumber": {
"type": "string",
"minLength": 1,
"description": "Employee number, must be at least 1 character long."
},
"submitterText": {
"type": "string",
"minLength": 1,
"description": "Text submitted by the user, must be at least 1 character long."
}
},
"required": [
"employeeNumber",
"submitterText"
], …
```

fix(core): fixed a bug with schema viewer not supporting schemas defined with "$ref"

---

.changeset/modern-seas-invent.md
eventcatalog/src/components/Grids/ServiceGrid.tsx

Fixed long list of messages on architecture page.
Now we limit the number of messages here.

fix(core): fixed issue with long list of messages on architecture page

---

.changeset/afraid-onions-applaud.md
eventcatalog/astro.config.mjs
src/eventcatalog.config.ts

Fix for #1579, compress is now optional, but enabled by default.
To turn off you need to add this to `eventcatalog.config.js`
```
compress: false
```

feat(core): compressing build is now optional

---

.changeset/moody-eyes-suffer.md
eventcatalog/astro.config.mjs

CSS compress seems to be causing issues in the project e.g custom styles, z index issues. (e.g https://github.com/event-catalog/eventcatalog/issues/1598)
Turning this off for EventCatalog (at least for now).

fix(core): no longer compress css

---

.changeset/witty-carrots-film.md
eventcatalog/src/components/CopyAsMarkdown.tsx
eventcatalog/src/content.config.ts
eventcatalog/src/pages/docs/[type]/[id]/[version]/index.astro
eventcatalog/src/utils/__tests__/url-builder.spec.ts
eventcatalog/src/utils/url-builder.ts

Fix for https://github.com/event-catalog/eventcatalog/issues/1605
- Added Edit Page in the dropdown for all pages (Copy Page)
- Added Edit Page button at the bottom of all pages

feat(core): added edit links into resource pages

---

.changeset/stupid-dancers-occur.md
eventcatalog/src/utils/collections/file-diffs.ts

Original AVRO-tool generate files with extension `avsc`, when it is used parameter `idl2schemata`. This merge request add support for avsc file diffs.

feature(core) Add support for avsc files in diffs

---

.changeset/sixty-ladybugs-wonder.md
eventcatalog/src/components/Grids/ServiceGrid.tsx

Some feedback from folks, that the architecture (Two) columns we causing issues, with long message names.
Suggestion was to move to single columns for these pages, which I'm happy with.
If anyone reading this wants two back again, we can add a toggle in the future. Until then single columns it is! Cheers!

chore(core): architecture pages now single column

---

.changeset/eighty-seas-glow.md
eventcatalog/src/content.config.ts

Fix for #1691
Enums and items are now shown correctly in the properties table.

fix(core): enums and items now shown on entity properties map

---

.changeset/clever-scissors-admire.md
eventcatalog/src/components/MDX/SchemaViewer/SchemaProperty.astro

JSON Schema supports the [const keyword](https://json-schema.org/understanding-json-schema/reference/const). This can be useful to represent values that don't change, e.g. a version number embedded within a message.
Where a value is constant, having this show in the Schema Viewer is valuable.
* At the moment none of the examples have this const keyword to demonstrate the feature, I'm happy to add this but I wanted to align before doing that. I could be add version numbers within messages to one (or more) messages within the existing examples.
* One test is failing on my machine, which seems unrelated to my changes, and appears to be due to a missing file. I can't see how that file should be generated.
```
FAIL |@eventcatalog/astro| …
```

feat(schema-viewer): display constant values in schema viewer

---

.changeset/metal-ears-relate.md
eventcatalog/src/components/CopyAsMarkdown.tsx
eventcatalog/src/utils/__tests__/url-builder.spec.ts
eventcatalog/src/utils/url-builder.ts

Fix for #1714
The generated URL for markdown now takes into consideration the trialing slash configuration for catalogs.

fix(core): fix copy button for trialing slash catalogs
