- .changeset/config.json
- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature.yml
- CONTRIBUTING.md
- website/docs/community/overview.md
Updating the branch, was pointing to the wrong one.
> docs: updating branch name in docs to point to the real one

- website/docusaurus.config.js
> docs: adding GA to website

- .changeset/silver-moose-argue.md
- examples/basic/events/AddedItemToCart/changelog.md
- examples/basic/events/AddedItemToCart/versioned/0.0.1/changelog.md
- examples/basic/events/AddedItemToCart/versioned/0.0.2/changelog.md
- examples/basic/events/AddedItemToCart/versioned/0.0.2/index.md
- examples/basic/events/AddedItemToCart/versioned/0.0.2/schema.json
- packages/create-eventcatalog/templates/default/events/AddedItemToCart/changelog.md
- packages/create-eventcatalog/templates/default/events/AddedItemToCart/schema.json
- packages/create-eventcatalog/templates/default/events/AddedItemToCart/versioned/0.0.1/changelog.md
- packages/create-eventcatalog/templates/default/events/AddedItemToCart/versioned/0.0.2/changelog.md
- packages/create-eventcatalog/templates/default/events/AddedItemToCart/versioned/0.0.2/index.md
- packages/create-eventcatalog/templates/default/events/AddedItemToCart/versioned/0.0.2/schema.json
- packages/eventcatalog/lib/events.ts
Change logs for events were confusing. They were inside the versioned folder and also outside into the main event folder.
Changelogs are now only in versioned folders allowing users to keep the changes local to the versioned events.
> feat: changelog.md files now belong inside the versioned folders

- .changeset/wise-bugs-play.md
- jest.config.js
- packages/eventcatalog-utils/README.md
- packages/eventcatalog-utils/package.json
- packages/eventcatalog-utils/src/__tests__/assets/catalog/events/OrderComplete/index.md
- packages/eventcatalog-utils/src/__tests__/assets/catalog/events/OrderComplete/schema.json
- packages/eventcatalog-utils/src/__tests__/assets/catalog/events/OrderCreated/index.md
- packages/eventcatalog-utils/src/__tests__/assets/catalog/events/OrderCreated/schema.json
- packages/eventcatalog-utils/src/__tests__/assets/catalog/services/Order Service/index.md
- packages/eventcatalog-utils/src/__tests__/assets/catalog_version_test/events/EventWithoutVersion/index.md
- packages/eventcatalog-utils/src/__tests__/assets/catalog_version_test/events/OrderComplete/index.md
- packages/eventcatalog-utils/src/__tests__/assets/catalog_version_test/events/OrderComplete/schema.json
- packages/eventcatalog-utils/src/__tests__/utils.spec.ts
- packages/eventcatalog-utils/src/index.ts
- packages/eventcatalog-utils/src/markdown-builder.ts
- packages/eventcatalog-utils/tsconfig.json
Adding new utils package for the EventCatalog, idea is the code will be shared between the core application and also plugin architecture.
> feat: added new utils package

- .changeset/hungry-seas-hope.md
- .gitignore
- packages/eventcatalog-utils/tsconfig.json
Added typescript declaration to eventcatalog-utils package to help developers use the package.
> fix: added typescript declaration to utils package

- .changeset/young-melons-fetch.md
- packages/eventcatalog-utils/src/index.ts
Small tidy on the code also trying to fix versioning with changesets...
> chore: tidy code

- .changeset/lucky-seals-brush.md
- packages/eventcatalog-utils/src/__tests__/assets/catalog/services/My Service That Already Exists/index.md
- packages/eventcatalog-utils/src/__tests__/utils.spec.ts
- packages/eventcatalog-utils/src/events.ts
- packages/eventcatalog-utils/src/index.ts
- packages/eventcatalog-utils/src/services.ts
- packages/eventcatalog-utils/src/types.ts
Added more util functions to the `eventcatalog-utils` package, to help people build plugins.
Docs still need writing and going to dogfood this API with the AsyncAPI plugin to see how it goes, more changes may come whilst this package is still being phased out.
> feat: added more utils with slight refactors

- .changeset/five-mirrors-decide.md
- packages/eventcatalog-types/src/index.d.ts
- packages/eventcatalog/components/Sidebars/ServiceSidebar.tsx
- packages/eventcatalog/lib/__tests__/assets/services/Basket Service/index.md
- packages/eventcatalog/lib/__tests__/services.spec.ts
- packages/eventcatalog/lib/services.ts
- website/docs/api/service-frontmatter.md
A PR to introduce the capability to add 1 or multiple external links for services.
yes
> feat: externalLinks for services

- .changeset/long-zoos-tell.md
- packages/eventcatalog/components/Sidebars/EventSidebar.tsx
- packages/eventcatalog/components/Sidebars/ServiceSidebar.tsx
Adding keys on maps that are missing.
> fix: adding keys on maps in react

- .changeset/silent-shrimps-rest.md
- packages/eventcatalog/pages/events/[name]/logs.tsx
> fix: event log page now displays correct name

- .changeset/cuddly-jars-kick.md
- packages/eventcatalog/package.json
- packages/eventcatalog/pages/events.tsx
From feedback, giving users the ability to search for events on the event page using an input.
> feat: adding search to events page

- packages/eventcatalog-plugin-generator-amazon-eventbridge/tsconfig.json
- packages/eventcatalog-plugin-generator-asyncapi/tsconfig.json
> Exclude output folders from being processed by tsc

- .changeset/cuddly-deers-carry.md
- packages/eventcatalog/next.config.js
- website/docs/api/eventcatalog.config.js.md
> Allow to configure "trailingSlash"

- .changeset/tidy-turkeys-sneeze.md
- packages/eventcatalog-plugin-generator-amazon-eventbridge/src/lib/aws.ts
Fix for issue #144
(Write your motivation here.)
> Fix: eventbridge targets rules await issue #144

- .changeset/good-lions-exercise.md
- .github/workflows/canary.yml
- packages/eventcatalog-plugin-generator-amazon-eventbridge/README.md
- packages/eventcatalog-plugin-generator-asyncapi/README.md
- packages/eventcatalog/README.md
Looks like for some reason the npm versions are out of sync and the latest versions were released as canary.... trying to bump them with small changes to readmes...
> fix: trying to fix npm versions problem

- .changeset/nice-foxes-beam.md
- packages/eventcatalog/lib/__tests__/graphs.spec.ts
- packages/eventcatalog/lib/graphs.ts
Bug fix where the services publish & subscribe got inverted.
Bug:
PR results:
yes
> fix: services publish & subscribe

- .changeset/shiny-ants-retire.md
- packages/eventcatalog/components/Header.tsx
> fix: header logo now reads from config

- .changeset/fuzzy-deers-yawn.md
- packages/eventcatalog/pages/events/[name].tsx
- packages/eventcatalog/pages/services/[name].tsx
Sometimes the MDX components have a default title and sometimes the title is optional.
For consistency, this PR makes the title property optional for all MDX components on the event and service pages
Yes
> fix: optional title for all MDX components

- .changeset/eight-carrots-thank.md
- packages/eventcatalog/pages/visualiser.tsx
Minor fixes for mobile for visualiser, not sure who uses it mobile... but thought I would fix it just in case, was quite broken.
> fixing visualiser for mobile devices

- .changeset/pretty-oranges-cough.md
- examples/basic/eventcatalog.config.js
- packages/create-eventcatalog/templates/default/eventcatalog.config.js
- packages/eventcatalog/components/Footer.tsx
- packages/eventcatalog/pages/visualiser.tsx
Added new footer link for visualiser and also fixed hover styles for footer links
> chore: added new footer link for visualiser

- website/docs/installation.md
Just saw a minor spelling error and it bugged me
I did, hope I did not miss anything
> docs: fix spelling mistake

- .changeset/chatty-seals-poke.md
- examples/basic/domains/Shopping/events/AddedItemToCart/versioned/0.0.1/changelog.md
- examples/basic/domains/Shopping/events/AddedItemToCart/versioned/0.0.2/changelog.md
- packages/eventcatalog/components/Sidebars/EventSidebar.tsx
- packages/eventcatalog/pages/domains/[domain]/events/[name]/logs.tsx
- packages/eventcatalog/pages/domains/[domain]/index.tsx
- packages/eventcatalog/pages/events/[name]/logs.tsx
- packages/eventcatalog/pages/events/[name]/v/[version].tsx
Fixing issues with domain mappings for static rendering and also fixing issues with change logs rendering incorrectly when having domain folders.
> fix: fixing domain mappings and change log issues with domains

- .changeset/nice-ads-stare.md
- packages/eventcatalog/pages/visualiser.tsx
Fix for #192 from @otbe 
When you click on the visualiser items, the query params are now updated allowing ease of sharing urls.
> feat: visualiser on click now sets query params

- .changeset/four-buckets-poke.md
- packages/eventcatalog/components/Mdx/NodeGraph/GraphElements.tsx
- packages/eventcatalog/components/Mdx/NodeGraph/GraphLayout.ts
- packages/eventcatalog/components/Mdx/NodeGraph/NodeGraph.tsx
- packages/eventcatalog/components/Mdx/NodeGraph/__tests__/__snapshots__/GraphElements.spec.ts.snap
- packages/eventcatalog/components/Mdx/NodeGraph/__tests__/__snapshots__/GraphLayout.spec.ts.snap
- packages/eventcatalog/pages/visualiser.tsx
#225
Changes
- Added new node on visualiser to allow users to see all services and events
- Removed code on the nodegraph to simplify the elements updating and rendering
- Fixed issues with visualiser throwing silent errors and re-rendering problems
- Fixed React issues with missing keys.
> feat: adding new node in visualiser to show all events and services

- .changeset/afraid-ants-promise.md
- packages/eventcatalog/components/Sidebars/EventSidebar.tsx
> Fix broken links for services that have no domain on events detail page

- .changeset/tender-adults-study.md
- packages/eventcatalog/pages/domains.tsx
- packages/eventcatalog/pages/events.tsx
- packages/eventcatalog/pages/services.tsx
Minor padding issues found on the domains, events and services pages just fixing them
> fix: fixing small padding issues on various pages

- .changeset/quick-seahorses-jump.md
- .changeset/shaggy-fans-design.md
- packages/eventcatalog/hooks/EventCatalog.tsx
Fixes #253
Want edit links to work for everyone. 😁
Yes, all good. 👍
> fix(core): Fixes getEditUrl to build URLs w/URL vs just path.join

- .changeset/clever-fireants-melt.md
- packages/eventcatalog/pages/services.tsx
Using the catalog, I noticed that the services section does not have the functionality to filter as the events section does.
yes ✌️ 🚀
> add search box in services page

- .changeset/eleven-hairs-serve.md
- packages/eventcatalog/components/Sidebars/EventSidebar.tsx
> fix: Broken link behind event's View in Visualiser button

- .changeset/perfect-cobras-join.md
- packages/eventcatalog/package.json
- yarn.lock
Updating mermaid to latest for features + security patches.
> chore - update mermaid package

- README.md
> Fix typo (keen -> keep)

- .changeset/curvy-numbers-search.md
- packages/eventcatalog/pages/_document.tsx
A few users have said about slow load times. This is a small attempt to help that, moving to minified files and moving away from slow CDN onto cloudflare for font-awesome.
> chore: updating to minify files and change cdn for font-awesome

- README.md
Fixed a typo and link.
Yes, afterwards %-). Went too fast to fix the typo.
> #352: Fixed typo and branch name.

- .changeset/smart-roses-leave.md
- packages/eventcatalog/components/NotFound/index.tsx
- packages/eventcatalog/pages/domains/[domain]/index.tsx
Found an issue not rendering the 404 page for domain pages.
> (fix) - fixing 404 issues with domain page

- website/docs/guides/upgrading.md
* Fixing wrong indentation for the `@eventcatalog/types` example.
* Removing unnecessary double quotes from the main description to ease the reading.
Yes.
> docs: fix migration guide style

- .changeset/sweet-peaches-press.md
- packages/eventcatalog/components/Grids/EventGrid.tsx
- packages/eventcatalog/components/Grids/ServiceGrid.tsx
- packages/eventcatalog/pages/events.tsx
- packages/eventcatalog/pages/services.tsx
The event grid and service grid now have a feature to show node graphs
Yes
> Show node graphs

- .changeset/lazy-years-attend.md
- examples/basic/domains/Orders/events/OrderCreated/index.md
- packages/eventcatalog/components/Mdx/OpenApiSpec.tsx
- packages/eventcatalog/pages/events/[name].tsx
- packages/eventcatalog/pages/services/[name].tsx
- website/docs/guides/events/events-adding-openapi.md
https://github.com/boyney123/eventcatalog/issues/387
This will now allow props to be used in the OpenAPI component.
> allow props to be used in openAPI components

- .changeset/purple-comics-wait.md
- packages/create-eventcatalog/templates/default/Dockerfile
- website/docs/guides/events/events-adding-openapi.md
- website/docs/guides/services/services-adding-openapi.md
Related to #319, this PR will allow people to build EventCatalog into a container.
> Fixing docker file for eventcatalog

- .changeset/happy-rings-exist.md
- packages/eventcatalog/package.json
After local installation was having some issues with the 'fs' library, when trying to redirect/load a service.
After include this on the package.json fixed it
[Fixes](https://github.com/boyney123/eventcatalog/issues/430)
> Chore: including fs false by default

- .changeset/sour-paws-appear.md
- packages/eventcatalog/components/Grids/ServiceGrid.tsx
> fix: set key on rendered serices, no longer duplicates them

- .changeset/short-dodos-shave.md
- examples/basic/eventcatalog.config.js
- packages/create-eventcatalog/templates/default/eventcatalog.config.js
- packages/eventcatalog/components/Grids/UserGrid.tsx
- packages/eventcatalog/components/Header.tsx
- packages/eventcatalog/hooks/EventCatalog.tsx
- packages/eventcatalog/pages/users.tsx
It is useful to have a page to list all the users configured in the catalog
Currently you can only review users one at a time, with this change the /users page is enabled
yes
> Added users page

- .changeset/clever-pumpkins-chew.md
- package.json
- yarn.lock
Was seeing high vulnerability issues with trim in yarn audit
Yes
> Added a resolution to force trim to 0.0.3 and fixing the audit for high vulnerability

- .changeset/soft-zebras-suffer.md
- packages/eventcatalog/package.json
- yarn.lock
Fix for #468 , reducing the version of the swagger component as the latest version breaks the build.
> fix - fixed build with swagger version

- .changeset/soft-flowers-hear.md
- packages/eventcatalog/bin/eventcatalog.js
> feat - copy over styles on dev and build

- .changeset/ninety-mice-dance.md
- packages/create-eventcatalog/templates/default/eventcatalog.styles.css
- packages/eventcatalog/bin/eventcatalog.js
- website/src/components/Hero.js
Fixing issue when copying styles over.
> fix: bug when copy styles over

- .changeset/long-pears-crash.md
- packages/eventcatalog/package.json
- website/src/components/Hero.js
- yarn.lock
fix render file asyncapi version 3.0.0
With file in `Account Service` folder (inside `services folder)
index.md
```markdown
---
name: Account Service
summary: |
Account service summary.
---
Foo bar baz.
<AsyncAPI />
```
asyncapi.yaml
```yaml
asyncapi: 3.0.0
info:
title: Account Service
version: 1.0.0
description: This service is in charge of processing user signups
channels:
userSignedup:
address: user/signedup
messages:
UserSignedUp:
$ref: '#/components/messages/UserSignedUp'
operations:
sendUserSignedup:
action: send
channel:
$ref: '#/channels/userSignedup'
messages:
- $ref: '#/channels/userSignedup/messages/UserSignedUp'
components:
messages:
UserSignedUp:
payload:
type: object
properties:
displayName:
type: string
description: Name of the user
email:
type: string
format: email …
```
> fix: render file asyncapi version 3.0.0

- .changeset/blue-kids-complain.md
- packages/eventcatalog/package.json
- yarn.lock
Update to latest version of mermaid.
> Update mermaid version to latest

- .changeset/ninety-bulldogs-begin.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- examples/default/eventcatalog.config.js
- examples/default/eventcatalog.styles.css
- src/layouts/CustomDocsPageLayout.astro
- src/pages/docs/[type]/[id]/[version]/index.astro
Updated EventCatalog URL to the new GitHub URL.
> chore(core): update the project url to the github org

- .changeset/two-starfishes-grin.md
- src/components/MDX/NodeGraph/Nodes/Command.tsx
- src/components/MDX/NodeGraph/Nodes/Event.tsx
- src/components/MDX/NodeGraph/Nodes/Service.tsx
* configure min-width and max-width for events/service/command nodes in visualise
> fix(core): configure width for nodes in visualiser (#560)

- .changeset/calm-horses-stare.md
- bin/eventcatalog.ts
> chore(core): testing builds

- .changeset/shiny-elephants-raise.md
- bin/eventcatalog.config.ts
- tsup.config.js
Want to add types for folks config files so they know which properties are supported in the JS file.
> feat(core): added types file for eventcatalog.config.js

- .changeset/two-sheep-reflect.md
- examples/default/commands/UpdateInventory/index.md
- examples/default/events/Inventory/InventoryAdjusted/index.md
- examples/default/events/Inventory/InventoryAdjusted/schema.json
- package-lock.json
- package.json
- src/components/MDX/Admonition.tsx
- src/components/MDX/SchemaViewer/SchemaViewer.astro
- src/components/MDX/SchemaViewer/SchemaViewer.module.css
- src/components/MDX/SchemaViewer/SchemaViewer.tsx
- src/components/MDX/SchemaViewer/SchemaViewerPortal.tsx
- src/components/MDX/components.tsx
- src/pages/docs/[type]/[id]/[version]/index.astro
- src/utils/commands.ts
- src/utils/domains/domains.ts
- src/utils/events.ts
- src/utils/services/services.ts
> feat(core): Adding <SchemaViewer /> component

- .changeset/gentle-ravens-compare.md
- .gitignore
- astro.config.mjs
- bin/eventcatalog.config.ts
- examples/default/eventcatalog.config.js
- src/components/DocsNavigation.astro
- src/components/Header.astro
- src/components/MDX/NodeGraph/NodeGraph.tsx
- src/components/Seo.astro
- src/components/Tables/columns/DomainTableColumns.tsx
- src/components/Tables/columns/MessageTableColumns.tsx
- src/components/Tables/columns/ServiceTableColumns.tsx
- src/layouts/CustomDocsPageLayout.astro
- src/layouts/DiscoverLayout.astro
- src/layouts/VisualiserLayout.astro
- src/pages/discover/[type]/index.astro
- src/utils/url-builder.ts
> feat(core): added support for base url and slashes 

- .changeset/small-turtles-run.md
- src/components/MDX/SchemaViewer/SchemaViewer.module.css
- src/components/MDX/SchemaViewer/SchemaViewer.tsx
> fix(core): fixed issues with styling

- .changeset/thick-seahorses-peel.md
- src/components/MDX/Accordion/Accordion.astro
- src/components/MDX/Accordion/AccordionGroup.astro
- src/pages/visualiser/[type]/[id]/[version]/index.astro
- src/pages/visualiser/index.astro
Removed console logs that have been left behind
> chore(core): removed console logs

- .changeset/warm-hounds-draw.md
- global.d.ts
- src/pages/docs/[type]/[id]/[version]/index.astro
- src/pages/visualiser/index.astro
Fixed additional ts errors with window objects.
> fix(core): fixed additional ts errors

- .changeset/yellow-otters-heal.md
- src/pages/docs/users/[id]/index.astro
A temporary fix for #609, rather than showing the wrong thing let's not show it.
Raising a new issue to display domains for users. Was more involved than I initially thought!
> fix(core): temp fix for domains for users

- .changeset/red-radios-teach.md
- src/pages/discover/[type]/index.astro
> fix(core): fixed performance issues for discover pages in build step

- .changeset/grumpy-dragons-hug.md
- astro.config.mjs
> fix(core): fixed search, now set output path on build

- .changeset/gold-trees-brake.md
- src/components/SideBars/DomainSideBar.astro
Minor update to fix https://github.com/event-catalog/eventcatalog/issues/641 
Yes
> fix(core): minor updated to render service list with name rather than id

- .changeset/late-chefs-peel.md
- astro.config.mjs
> Fix missing base in redirect target

- .changeset/forty-pillows-add.md
- src/components/Tables/Table.tsx
- src/components/Tables/columns/DomainTableColumns.tsx
- src/components/Tables/columns/MessageTableColumns.tsx
- src/components/Tables/columns/ServiceTableColumns.tsx
> fix(core): discover table width now fixed on long summarys

- .changeset/chatty-comics-yawn.md
- examples/default/pages/index.md
- scripts/catalog-to-astro-content-directory.js
- scripts/default-files-for-collections/pages.md
- scripts/watcher.js
- src/components/MDX/page-components.tsx
- src/content/config.ts
- src/layouts/DocsLayout.astro
- src/pages/docs/index.astro
- src/pages/docs/index.md
- src/utils/pages.ts
Fixed #640
Added ability to customize the index page, add new folder called `pages`. (Support for future custom pages may be considered).
> feat(core):customize the landing page

- .changeset/five-wasps-itch.md
- examples/default/events/Inventory/InventoryAdjusted/versioned/1.0.0/index.md
- src/pages/docs/[type]/[id]/[version]/changelog/index.astro
> fix(core): fixed urls on changelogs

- .changeset/silver-phones-destroy.md
- src/components/SideBars/DomainSideBar.astro
- src/components/SideBars/MessageSideBar.astro
- src/components/SideBars/ServiceSideBar.astro
> fix(core): fixed changelog urls on resource pages

- .prettierrc
- package-lock.json
- package.json
- src/components/DocsNavigation.astro
- src/components/Header.astro
- src/components/Lists/VersionList.astro
- src/components/MDX/Accordion/Accordion.astro
- src/components/MDX/Accordion/AccordionGroup.astro
- src/components/MDX/NodeGraph/NodeGraph.astro
- src/components/MDX/SchemaViewer/SchemaViewer.astro
- src/components/Search.astro
- src/components/Seo.astro
- src/components/SideBars/DomainSideBar.astro
- src/components/SideBars/MessageSideBar.astro
- src/components/SideBars/ServiceSideBar.astro
- src/layouts/CustomDocsPageLayout.astro
- src/layouts/DiscoverLayout.astro
- src/layouts/DocsLayout.astro
- src/layouts/Footer.astro
- src/pages/discover/[type]/index.astro
- src/pages/docs/[type]/[id]/[version]/changelog/index.astro
- src/pages/docs/[type]/[id]/[version]/index.astro
- src/pages/docs/index.astro
- src/pages/docs/teams/[id]/index.astro
- src/pages/docs/users/[id]/index.astro
- src/pages/visualiser/[type]/[id]/[version]/index.astro
Nice idea from @otbe , added astro prettier plugin to help with contributions and code style guide etc.
> chore(core): added prettier for astro iles

- .changeset/dry-crews-applaud.md
- src/pages/docs/[type]/[id]/index.astro
It adds a redirect page for the latest version. 
Resolves #689.
> feat: add page redirect to latest version

- .changeset/shiny-dodos-develop.md
- examples/default/events/Payment/PaymentProcessed/versioned/0.0.1/index.md
- examples/default/services/InventoryService/index.md
- examples/default/services/InventoryService/versioned/0.0.1/index.md
- examples/default/services/NotificationService/index.md
- package-lock.json
- package.json
- src/content/config.ts
- src/utils/__tests__/commands/node-graph.spec.ts
- src/utils/__tests__/events/node-graph.spec.ts
- src/utils/__tests__/services/node-graph.spec.ts
- src/utils/commands.ts
- src/utils/events.ts
- src/utils/services/node-graph.ts
- src/utils/services/services.ts
It adds semantic version range to specify receives/sends with valid version range.
Resolves #646
> feat: add semantic version range

- .changeset/dull-impalas-enjoy.md
- src/layouts/VisualiserLayout.astro
Change in sidebar of visualiser to only show latest versions
> Fix #700 : Only show latest versions on visualiser page

- .changeset/thin-feet-eat.md
- examples/default/domains/Orders/index.md
- examples/default/flows/Subscriptions/CancelSubscription/versioned/0.0.1/index.md
- src/components/MDX/Flow/Flow.astro
- src/components/MDX/NodeGraph/NodeGraph.tsx
- src/components/MDX/components.tsx
- src/pages/docs/[type]/[id]/[version]/index.astro
- src/utils/flows/flows.ts
- src/utils/flows/node-graph.ts
- src/utils/services/node-graph.ts
- src/utils/services/services.ts
- src/utils/versions/versions.ts
Added new Flow component for MDX pages
> feat(core): added new MDX component for Flows

- .changeset/eight-eggs-confess.md
- README.md
- scripts/generate.js
> forcing a new release

- .changeset/yellow-ligers-perform.md
- src/pages/docs/[type]/[id]/[version]/asyncapi/index.astro
- src/pages/docs/[type]/[id]/[version]/changelog/index.astro
- src/pages/docs/[type]/[id]/[version]/index.astro
- src/pages/docs/[type]/[id]/[version]/spec/index.astro
- src/pages/visualiser/[type]/[id]/[version]/index.astro
- src/types/index.ts
- src/utils/messages.ts
- src/utils/pages/pages.ts
Just a tidy up on the pages, hopefully simplifying them and reducing code along the way. Part of the refactor that will enable queries.
> chore(core): refactored the way pages are rendered reducing code

- .changeset/afraid-drinks-smell.md
- src/utils/changelogs/changelogs.ts
> fix(core): fixed changelogs path matching

- .changeset/kind-geese-type.md
- src/pages/discover/[type]/index.astro
> dont generate discover pages for each item in a type collection

- .changeset/tricky-sloths-occur.md
- examples/default/domains/Orders/index.md
- examples/default/eventcatalog.config.js
- examples/default/events/Inventory/InventoryAdjusted/index.md
- examples/default/services/InventoryService/index.md
- examples/default/services/NotificationService/index.md
- examples/default/services/OrdersService/index.md
- examples/default/services/SubscriptionService/index.md
- package-lock.json
- src/components/MDX/Tiles/Tile.astro
- src/components/MDX/Tiles/Tiles.astro
- src/components/MDX/components.tsx
Added new tile components to EventCatalog.
> feat(core): added tile MDX components

- .changeset/lazy-sheep-sparkle.md
- src/utils/users.ts
Updated #667, just added it as a new PR
> fix(core): user ownership on resources within a team

- .changeset/tiny-falcons-protect.md
- scripts/eventcatalog-config-file-utils.js
Attempt to fix https://github.com/event-catalog/generator-asyncapi/issues/39
> fix(core): fixed windows issue for fetching config files

- package.json
> Added property `homepage` and `repository` to package.json

- .changeset/flat-scissors-think.md
- src/pages/docs/[type]/[id]/[version]/index.astro
> chore(core): fixed css issues with badges on pages

- .changeset/moody-hounds-travel.md
- package.json
- scripts/build-ci.js
> Removed type checks for consuming catalogs

- .changeset/fresh-files-sit.md
- src/components/MDX/SchemaViewer/SchemaViewer.astro
- src/content/config.ts
- src/utils/commands.ts
- src/utils/domains/domains.ts
- src/utils/events.ts
- src/utils/flows/flows.ts
- src/utils/services/services.ts
Small change to help with supporting new folder structures in the future. Added and using the Astro file path as the file for SchemaViewer.
> chore(core): added astro file path to resources

- .changeset/dull-meals-accept.md
- package-lock.json
- package.json
- scripts/__tests__/eventcatalog-config-file-utils.spec.ts
- scripts/eventcatalog-config-file-utils.js
> Consider --- in addPropertyToFrontMatter

- .changeset/loud-students-help.md
- astro.config.mjs
> feat(core): added support for outDir

- .changeset/rotten-numbers-admire.md
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
- eventcatalog/src/hooks/eventcatalog-visualizer.ts
- eventcatalog/src/utils/__tests__/events/node-graph.spec.ts
- eventcatalog/src/utils/__tests__/services/node-graph.spec.ts
- eventcatalog/src/utils/node-graphs/message-node-graph.ts
- eventcatalog/src/utils/node-graphs/utils/utils.ts
> feat(core): added ability to turn channels on/off

- .changeset/chatty-islands-smoke.md
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
- package-lock.json
> feat(core): added ability to zoom out even further in visualizer

- .changeset/six-melons-glow.md
- eventcatalog/src/components/Tables/columns/ServiceTableColumns.tsx
Fix for #956
Services now show collapsed messages when the column has over 10 messages.
> feat(core): services in the discover table now shows expandable sections

- .changeset/yellow-games-itch.md
- eventcatalog/src/components/SideBars/CatalogResourcesSideBar/index.tsx
> feat(core): sidebar collapsed states now persisted between page loads

- .changeset/loud-days-pump.md
- default-files-for-collections/ubiquitousLanguages.md
- eventcatalog/src/components/SideBars/DomainSideBar.astro
- eventcatalog/src/content/config.ts
- eventcatalog/src/pages/docs/[type]/[id]/language.astro
- eventcatalog/src/utils/__tests__/domains/domains.spec.ts
- eventcatalog/src/utils/__tests__/domains/mocks.ts
- eventcatalog/src/utils/collections/domains.ts
- eventcatalog/src/utils/collections/icons.ts
- examples/default/domains/Orders/ubiquitous-language.md
- examples/default/domains/Payment/ubiquitous-language.md
- examples/default/domains/Subscriptions/ubiquitous-language.md
- src/__tests__/catalog-to-astro-content-directory.spec.ts
- src/__tests__/example-catalog/domains/Payment/ubiquitous-language.md
- src/catalog-to-astro-content-directory.js
- src/map-catalog-to-astro.js
Added new feature for ubiquitous language support.
> feat(core): added ubiquitous language support

- .changeset/few-pears-battle.md
- eventcatalog/src/components/MDX/NodeGraph/Edges/AnimatedMessageEdge.tsx
> fix(core): fixed issue rendering animated nodes with flow diagrams

- .changeset/young-dragons-call.md
- eventcatalog/src/components/MDX/Tabs/TabItem.astro
- eventcatalog/src/components/MDX/Tabs/Tabs.astro
- eventcatalog/src/components/MDX/components.tsx
- examples/default/domains/Orders/services/InventoryService/events/InventoryAdjusted/index.md
Adding new `<Tabs>` and `<TabItem>` component to EventCatalog, letting users create tabs in their docs.
> feat(core): added new <Tabs> component

- .changeset/quick-hounds-worry.md
- src/eventcatalog.ts
> feat: forward extra args to astro cli via `--`

- .changeset/breezy-chefs-appear.md
- eventcatalog/astro.config.mjs
- eventcatalog/src/components/MDX/components.tsx
- eventcatalog/src/remark-plugins/directives.ts
- examples/default/domains/Orders/index.md
- examples/default/domains/Orders/services/InventoryService/events/InventoryAdjusted/versioned/0.0.1/index.md
- examples/default/domains/Orders/versioned/0.0.2/index.md
- package-lock.json
- package.json
- src/__tests__/example-catalog/events/Inventory/InventoryAdjusted/versioned/0.0.1/index.md
Added support for admonitions in EventCatalog using markdown.
```md
:::info
This is an info block
:::
:::tip
This is a tip block
:::
:::note
This is a note block
:::
:::warning
This is a warning block
:::
```
> feat(core): added admonitions using markdown

- .changeset/smooth-hounds-unite.md
- eventcatalog/src/layouts/VerticalSideBarLayout.astro
> fix broken context map link in sidebar

- .changeset/swift-meals-sip.md
- eventcatalog/src/utils/collections/domains.ts
> fix(core): ubiquitous lang now renders on domains

- .changeset/moody-ligers-retire.md
- eventcatalog/src/utils/channels.ts
- eventcatalog/src/utils/collections/domains.ts
- eventcatalog/src/utils/collections/flows.ts
- eventcatalog/src/utils/collections/services.ts
- eventcatalog/src/utils/commands.ts
- eventcatalog/src/utils/events.ts
- eventcatalog/src/utils/queries.ts
- eventcatalog/src/utils/teams.ts
- eventcatalog/src/utils/users.ts
> feat(core): resources across eventcatalog are now ordered by name

- .changeset/nine-monkeys-return.md
- eventcatalog/src/icons/protocols/index.ts
- eventcatalog/src/icons/protocols/kinesis.svg
Added Kinesis support for channels, closes #1067
> feat(core): added kinesis protocol to channels

- .changeset/four-socks-tap.md
- eventcatalog/src/utils/__tests__/collections/util.spec.ts
- eventcatalog/src/utils/collections/util.ts
> Sort versions by semver if all versions can be coerced to semver

- .changeset/beige-moles-hunt.md
- eventcatalog/src/pages/docs/[type]/[id]/language/[dictionaryId]/index.astro
> Dont render ul page if nothing is in the collection

- .changeset/fluffy-pumpkins-yawn.md
- eventcatalog/src/utils/collections/changelogs.ts
> Use slug to find specific changelogs via slug (instead of id)

- .changeset/purple-swans-try.md
- package.json
- pnpm-lock.yaml
- src/eventcatalog.ts
> chore(core): added catalog update version check

- .changeset/three-deers-protect.md
- .gitignore
- eventcatalog/src/enterprise/ai-assistant/components/Chat.tsx
- eventcatalog/src/enterprise/ai-assistant/components/ChatWindow.tsx
- eventcatalog/src/enterprise/ai-assistant/components/workers/document-importer.ts
- eventcatalog/src/pages/chat/index.astro
- package.json
- scripts/preview-catalog-locally.js
To get the workers working, I moved the files to the public directory so workers can get them and cache them
> fix(plugin): moved the generated ai file location to public dir

- .changeset/swift-pens-doubt.md
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Channel.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Command.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Event.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/MessageContextMenu.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Query.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Service.tsx
- package.json
- pnpm-lock.yaml
Added the ability to right click on nodes in visualizer.
This gives user the ability to quickly find things they are after, depending on the node type
> feat(core): added context menus to all nodes in visualizer

- .changeset/rich-mails-rush.md
- eventcatalog/src/components/Lists/OwnersList.tsx
- eventcatalog/src/components/Lists/PillListFlat.tsx
- eventcatalog/src/components/Lists/RepositoryList.astro
- eventcatalog/src/components/Lists/VersionList.astro
- eventcatalog/src/components/MDX/MessageTable/MessageTable.astro
- eventcatalog/src/components/MDX/MessageTable/MessageTable.client.tsx
- eventcatalog/src/components/MDX/components.tsx
- eventcatalog/src/components/SideBars/DomainSideBar.astro
- eventcatalog/src/components/SideBars/ServiceSideBar.astro
- eventcatalog/src/enterprise/ai-assistant/components/ChatSidebar.tsx
- eventcatalog/src/utils/collections/domains.ts
- examples/default/domains/Orders/index.md
- examples/default/domains/Orders/services/InventoryService/index.md
- examples/default/domains/Orders/services/NotificationService/index.md
- examples/default/domains/Orders/services/OrdersService/index.md
- examples/default/domains/Payment/index.md
- examples/default/domains/Payment/services/PaymentService/index.md
- examples/default/domains/Subscriptions/index.md
- examples/default/domains/Subscriptions/services/SubscriptionService/index.md
Added the following
- New `<MessageTable/>` component so messages can be seen and filtered on service/domain pages
- Domains now show the messages they send/receive based on the services part of them
> feat(core): added new message table component

- .changeset/tidy-flowers-sparkle.md
- eventcatalog/src/pages/chat/index.astro
I clicked the link and it didn't work.
> Fix typo in link for AI instructions

- .changeset/twenty-actors-type.md
- eventcatalog/src/components/SideNav/ListViewSideBar/components/MessageList.tsx
- eventcatalog/src/components/SideNav/ListViewSideBar/index.tsx
fixed issue with nav bar and selecting the correct page (styles only)
> fix(core): fixed styles in nav bar

- .changeset/nasty-chairs-prove.md
- eventcatalog/src/components/SideNav/ListViewSideBar/components/MessageList.tsx
- eventcatalog/src/components/SideNav/ListViewSideBar/utils.ts
- eventcatalog/src/content.config.ts
- examples/default/domains/Orders/services/InventoryService/commands/AddInventory/index.md
- examples/default/domains/Orders/services/InventoryService/commands/DeleteInventory/index.md
- examples/default/domains/Orders/services/InventoryService/commands/PlaceOrder/index.md
- examples/default/domains/Orders/services/InventoryService/commands/UpdateInventory/index.md
- examples/default/domains/Orders/services/InventoryService/index.md
- examples/default/domains/Orders/services/NotificationService/queries/GetNotificationDetails/index.md
- examples/default/domains/Orders/services/NotificationService/queries/GetUserNotifications/index.md
- examples/default/domains/Orders/services/OrdersService/queries/GetOrder/index.md
- examples/default/domains/Orders/services/ShippingService/commands/CancelShipment/index.md
- examples/default/domains/Orders/services/ShippingService/commands/CreateReturnLabel/index.md
- examples/default/domains/Orders/services/ShippingService/commands/CreateShipment/index.md
- examples/default/domains/Orders/services/ShippingService/commands/UpdateShipmentStatus/index.md
- examples/default/domains/Payment/services/PaymentService/queries/GetPaymentStatus/index.md
- examples/default/domains/Subscriptions/services/SubscriptionService/commands/CancelSubscription/index.md
- examples/default/domains/Subscriptions/services/SubscriptionService/commands/SubscribeUser/index.md
- examples/default/domains/Subscriptions/services/SubscriptionService/queries/GetSubscriptionStatus/index.md
Added the ability to customize the labels for messages in the `LIST_VIEW` sidebar.
> feat(core): customize sidebar labels and badge for messages

- .changeset/sweet-onions-train.md
- eventcatalog/src/pages/rss/[resource]/rss.xml.js
> fix(core): rss pages now render OK with empty catalog

- .changeset/nine-coins-grow.md
- eventcatalog/src/layouts/VerticalSideBarLayout.astro
- src/catalog-to-astro-content-directory.js
- src/eventcatalog.config.ts
> feat(core): sidebar items can now be hidden

- .changeset/stupid-ties-confess.md
- LICENSE.md
- eventcatalog/src/components/MDX/Tiles/Tile.astro
- eventcatalog/src/components/MDX/Tiles/Tiles.astro
- eventcatalog/src/content.config.ts
- eventcatalog/src/pages/docs/_default-docs.mdx
- eventcatalog/src/pages/docs/index.astro
- eventcatalog/src/utils/pages.ts
- examples/default/domains/Orders/index.mdx
- examples/default/pages/index.mdx
• Fixed an issue with `pages/index.mdx` not showing
• Enabled MDX components on the custom page
• Changes to Tile component to specify colors of icons and the columns.
> fix(core): fixed custom pages/index.mdx not showing in eventcatalog

- .changeset/smooth-ants-juggle.md
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Custom.tsx
- eventcatalog/src/content.config.ts
- eventcatalog/src/utils/node-graphs/flows-node-graph.ts
- eventcatalog/tailwind.config.mjs
- examples/default/domains/Subscriptions/flows/SubscriptionRenewed/index.mdx
- package.json
- pnpm-lock.yaml
> feat(core): added ability to add custom nodes in flows

- .changeset/gold-pets-ring.md
- eventcatalog/src/components/MDX/Link/Link.astro
- eventcatalog/src/components/MDX/ResourceLink/ResourceLink.astro
- eventcatalog/src/components/MDX/components.tsx
Added new components to MDX
• Link
• ResourceLink
These allow users to create links in there docs, but using there configured project, for example slash configuration etc.
> feat(core): added new link components

- .changeset/forty-numbers-type.md
- eventcatalog/src/pages/docs/custom/[...path].mdx.ts
- eventcatalog/src/pages/docs/llm/llms-full.txt.ts
- eventcatalog/src/pages/docs/llm/llms.txt.ts
added support for llms-txt for custom docs.
> feat(core): added llms-txt support for custom docs

- .changeset/smart-books-study.md
- eventcatalog/src/components/Lists/CustomSideBarSectionList.astro
- eventcatalog/src/components/MDX/ResourceGroupTable/ResourceGroupTable.astro
- eventcatalog/src/components/MDX/ResourceLink/ResourceLink.astro
- eventcatalog/src/components/MDX/SchemaViewer/SchemaViewer.astro
- eventcatalog/src/components/MDX/components.tsx
- eventcatalog/src/enterprise/custom-documentation/pages/docs/custom/index.astro
- eventcatalog/src/utils/__tests__/markdown.spec.ts
- eventcatalog/src/utils/collections/util.ts
- eventcatalog/src/utils/markdown.ts
- examples/default/docs/guides/creating-new-microservices/01-index.mdx
This enables the visualizer (NodeGraph) to be embedded within the custom documentation pages
> feat(core): embed visualizer into custom docs

- .changeset/stupid-squids-change.md
- eventcatalog/src/components/MDX/Miro/Miro.astro
Fix for URLs for miro component
> feat(core): added miro components to eventcatalog

- .changeset/rude-points-protect.md
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
Quality of life improvement
- Visualizer no longer zooms when moving nodes/edges
> fix(core): visualizer no longer zoomes on moving nodes

- .changeset/three-timers-sniff.md
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Channel.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Command.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Event.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Query.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Service.tsx
- eventcatalog/src/content.config.ts
• Added ability to customize nodes in visualizer
• The label will now read the customize label > sidebar label > fall back to what we already had.
Fix for #1352
> feat(core): added customization to nodes in visualizer

- .changeset/lovely-pigs-compete.md
- eventcatalog/src/content.config.ts
- eventcatalog/src/pages/docs/[type]/[id]/[version]/index.astro
- eventcatalog/src/utils/__tests__/collections/util.spec.ts
- eventcatalog/src/utils/collections/util.ts
The `deprecation` field for resources now also accepts boolean flags.
> feat(core): deprecation field now supports booleans

- .changeset/honest-hornets-cover.md
- eventcatalog/src/components/MDX/SchemaViewer/SchemaViewer.astro
- examples/default/domains/Orders/services/InventoryService/commands/UpdateInventory/schema.json
Adding more usecases for schema viewer to help #1333
> fix(core): update to schema viewer

- .changeset/small-jars-end.md
- eventcatalog/src/pages/docs/[type]/[id]/[version]/changelog/index.astro
- examples/default/domains/E-Commerce/index.mdx
Small fix for builds and adding missing files.
> feat(core): added support for subdomains

- .changeset/cold-rings-mate.md
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Flow.tsx
- eventcatalog/src/content.config.ts
- eventcatalog/src/utils/node-graphs/flows-node-graph.ts
- examples/default/domains/Payment/flows/PaymentProcessed/index.mdx
Proof of Concept for [issue #1378](https://github.com/event-catalog/eventcatalog/issues/1378). All relevant details can be found in the issue.
~~The PR is ready for review, but it's marked as a Draft until the issue receives approval.~~
> feat(core): allow flows to reference other flows

- .changeset/late-nails-call.md
- package.json
- pnpm-lock.yaml
Update to Eventcatalog SDK version
> update SDK version for demo

- .changeset/yellow-suns-invent.md
- eventcatalog/src/components/MDX/Lucid/Lucid.astro
- eventcatalog/src/components/MDX/components.tsx
- examples/default/docs/guides/event-storming/01-index.mdx
- examples/default/domains/E-Commerce/index.mdx
Added ability to embed Lucid diagrams into EventCatalog `<Lucid/>` component
> feat(core): added support for lucid component

- .changeset/few-ads-mix.md
- eventcatalog/src/pages/docs/[type]/[id]/[version]/index.astro
Add missing query badge.
https://demo.eventcatalog.dev/docs/queries/GetInventoryStatus/0.0.1
> fix(core): add missing query badge

- .changeset/three-seahorses-call.md
- eventcatalog/src/components/MDX/FigJam/FigJam.astro
- eventcatalog/src/components/MDX/components.tsx
Added new `<FigJam/>` component
> feat(core): added figjam component

- .changeset/forty-gifts-allow.md
- src/features.ts
Embedding now works with Scale Plan
> fix(core): embedding now works with scale plan

- .changeset/five-pets-fold.md
- eventcatalog/src/enterprise/eventcatalog-chat/components/ChatMessage.tsx
- eventcatalog/src/enterprise/eventcatalog-chat/components/InputModal.tsx
- eventcatalog/src/enterprise/eventcatalog-chat/components/WelcomePromptArea.tsx
- eventcatalog/src/enterprise/eventcatalog-chat/components/default-prompts.ts
- eventcatalog/src/enterprise/eventcatalog-chat/components/hooks/ChatProvider.tsx
- eventcatalog/src/enterprise/eventcatalog-chat/components/windows/ChatWindow.server.tsx
- eventcatalog/src/enterprise/eventcatalog-chat/pages/chat/index.astro
- eventcatalog/src/pages/chat/index.astro
- examples/default/chat-prompts/learning/what-events-are-relevant-to-this-feature.mdx
- package.json
- pnpm-lock.yaml
- src/catalog-to-astro-content-directory.js
- src/eventcatalog.ts
- src/map-catalog-to-astro.js
Changed:
- Added .env support for EventCatalog
- Added default prompts for people that use there own models without bringing any prompts
- Added the abilty to see generated prompts (system prompts) if they are generated for you
> feat(core): env file support and eventcatalog chat updates

- .changeset/tender-pianos-smell.md
- src/eventcatalog.ts
Fixed start command for the EventCatalog bin, now works with server based catalogs.
> fix(core): fixed start command for server catalogs

- .changeset/seven-penguins-pump.md
- eventcatalog/src/components/CopyAsMarkdown.tsx
- eventcatalog/src/components/SideBars/MessageSideBar.astro
- eventcatalog/src/enterprise/eventcatalog-chat/components/windows/ChatWindow.client.tsx
- eventcatalog/src/enterprise/eventcatalog-chat/components/windows/ChatWindow.server.tsx
- eventcatalog/src/pages/docs/[type]/[id]/[version]/index.astro
- eventcatalog/src/utils/__tests__/features.spec.ts
- eventcatalog/src/utils/__tests__/schemas/schemas.spec.ts
- eventcatalog/src/utils/collections/schemas.ts
- eventcatalog/src/utils/feature.ts
- examples/default/eventcatalog.config.js
- package.json
- pnpm-lock.yaml
- Added ability to copy pages to clipboard.
- Added ability to copy specs/schemas to clipboards
- Added quick link to talk to your page through Chat. (optional)
> feat(core): added ability to copy pages and schemas to clipboard

- .changeset/moody-icons-check.md
- examples/default/teams/full-stack.mdx
- src/__tests__/example-catalog/teams/full-stack.md
> chore: fix typo

- .changeset/dirty-lions-destroy.md
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Service.tsx
- eventcatalog/src/pages/docs/[type]/[id]/[version]/index.astro
- eventcatalog/src/utils/collections/schemas.ts
- Fixing issues with types for specifications
- Fixing issues with badges for specifications
> fix(core): fixing badges for specification files and types

- .changeset/random-schools.md
- src/eventcatalog.ts
removed glob-loader warnings from dev mode.
> efix(core): removed glob-loader warnings from dev

- .changeset/salty-wombats-brake.md
- eventcatalog/src/utils/node-graphs/utils/utils.ts
- examples/default/eventcatalog.config.js
- src/eventcatalog.config.ts
Allow channels node to be displayed as a single node per configuration (Fixing #989)
> Allow channels to be displayed as a single node (Fix #989)

- .changeset/purple-actors-sip.md
- eventcatalog/src/components/SideBars/ChannelSideBar.astro
- eventcatalog/src/utils/__tests__/services/mocks.ts
- eventcatalog/src/utils/__tests__/services/services.spec.ts
- eventcatalog/src/utils/collections/services.ts
> feat(core): added producers and consumers to channel docs

- .changeset/bright-peaches-pull.md
- eventcatalog/src/pages/docs/[type]/[id]/[version]/asyncapi/[filename].astro
> fix(core): fixed broken zindex for search on asyncapi page

- .changeset/strange-emus-enjoy.md
- eventcatalog/src/components/SideBars/ChannelSideBar.astro
- eventcatalog/src/components/SideBars/DomainSideBar.astro
- eventcatalog/src/components/SideBars/EntitySideBar.astro
- eventcatalog/src/components/SideBars/FlowSideBar.astro
- eventcatalog/src/components/SideBars/MessageSideBar.astro
- eventcatalog/src/components/SideBars/ServiceSideBar.astro
- eventcatalog/src/pages/docs/[type]/[id]/[version]/changelog/index.astro
- eventcatalog/src/utils/feature.ts
- src/eventcatalog.config.ts
> feat(core): added ability to turn off changelogs

- .changeset/late-jokes-pump.md
- eventcatalog/auth.config.ts
- eventcatalog/src/pages/auth/login.astro
- examples/default/eventcatalog.auth.js
- src/eventcatalog.auth.ts
> feat(core): added entra to auth providers

- .changeset/proud-pets-brush.md
- eventcatalog/src/components/MDX/SchemaViewer/SchemaProperty.astro
- eventcatalog/src/components/MDX/SchemaViewer/SchemaViewer.astro
> fix(core): fix for schema viewer

- .changeset/lovely-stingrays-raise.md
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
- eventcatalog/src/components/MDX/NodeGraph/StepWalkthrough.tsx
Added ability to walk through nodes in flows.
> feat(core): added node walkthroughs for flows

- .changeset/tasty-numbers-perform.md
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.astro
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
- eventcatalog/src/components/MDX/NodeGraph/Nodes/Domain.tsx
- eventcatalog/src/components/MDX/NodeGraph/VisualiserSearch.tsx
- eventcatalog/src/components/SideNav/ListViewSideBar/index.tsx
- eventcatalog/src/components/SideNav/ListViewSideBar/types.ts
- eventcatalog/src/components/SideNav/ListViewSideBar/utils.ts
- eventcatalog/src/pages/visualiser/domain-integrations/index.astro
- eventcatalog/src/utils/__tests__/domains/domains-canvas.spec.ts
- eventcatalog/src/utils/node-graphs/domains-canvas.ts
- examples/default/domains/E-Commerce/subdomains/Payment/index.mdx
- examples/default/domains/E-Commerce/subdomains/Payment/services/FraudDetectionService/events/FraudCheckCompleted/index.mdx
- examples/default/domains/E-Commerce/subdomains/Payment/services/FraudDetectionService/events/FraudCheckCompleted/schema.json
- examples/default/domains/E-Commerce/subdomains/Payment/services/FraudDetectionService/index.mdx
- examples/default/domains/E-Commerce/subdomains/Payment/services/PaymentGatewayService/commands/ProcessPayment/index.mdx
- examples/default/domains/E-Commerce/subdomains/Payment/services/PaymentGatewayService/commands/ProcessPayment/schema.json
- examples/default/domains/E-Commerce/subdomains/Payment/services/PaymentGatewayService/events/PaymentFailed/index.mdx
- examples/default/domains/E-Commerce/subdomains/Payment/services/PaymentGatewayService/events/PaymentFailed/schema.json
- examples/default/domains/E-Commerce/subdomains/Payment/services/PaymentGatewayService/index.mdx
- examples/default/domains/E-Commerce/subdomains/Subscriptions/index.mdx
- examples/default/domains/E-Commerce/subdomains/Subscriptions/services/BillingService/events/SubscriptionPaymentDue/index.mdx
- examples/default/domains/E-Commerce/subdomains/Subscriptions/services/BillingService/events/SubscriptionPaymentDue/schema.json
- examples/default/domains/E-Commerce/subdomains/Subscriptions/services/BillingService/index.mdx
- examples/default/domains/E-Commerce/subdomains/Subscriptions/services/PlanManagementService/index.mdx
Added a new visualizer page that will show you integration messages between your domains. To see the page you have to have domains in your catalog.
This will help users find messages that are being used to communicate between domains.
> feat(core): added domain integration visualizer

- .changeset/fluffy-pets-joke.md
- eventcatalog/astro.config.mjs
- eventcatalog/src/layouts/VerticalSideBarLayout.astro
- package.json
- pnpm-lock.yaml
Links added to headers in docs, allowing users to get the link to the heading.
> feat(core): added ability to link to headings

- .changeset/yellow-apes-relate.md
- eventcatalog/src/components/SideNav/ListViewSideBar/index.tsx
- eventcatalog/src/enterprise/custom-documentation/components/CustomDocsNav/index.tsx
- eventcatalog/src/layouts/VerticalSideBarLayout.astro
• Sidebar now has buttons to collapse the sidebar
• Sidebar now has expand/collapse buttons for items in the sidebar
• Subdomains are now grouped under domains in nav bar
> feat(core): sidebar now has collapse buttons

- .changeset/wise-adults-sniff.md
- eventcatalog/src/components/SideBars/ChannelSideBar.astro
- eventcatalog/src/components/SideBars/DomainSideBar.astro
- eventcatalog/src/components/SideBars/EntitySideBar.astro
- eventcatalog/src/components/SideBars/FlowSideBar.astro
- eventcatalog/src/components/SideBars/MessageSideBar.astro
- eventcatalog/src/components/SideBars/ServiceSideBar.astro
- eventcatalog/src/content.config.ts
- examples/default/domains/E-Commerce/subdomains/Orders/entities/Customer/index.mdx
Added the ability to customize the detail panels of all pages
This first version will give users ability to show/hide sections on this panel
> feat(core): added ability to customize detail panels on all pages

- .changeset/fuzzy-cobras-hide.md
- eventcatalog/src/components/Search/Search.astro
> fix(core): pagefind now includes the base config param

- .changeset/tricky-ties-search.md
- eventcatalog/src/components/Grids/MessageGrid.tsx
- eventcatalog/src/utils/commands.ts
- eventcatalog/src/utils/events.ts
- eventcatalog/src/utils/queries.ts
> fix(core): fixed architecture page for filtered messages with services

- .changeset/green-ways-wave.md
- eventcatalog/src/components/MDX/NodeGraph/NodeGraph.tsx
- eventcatalog/src/components/MDX/NodeGraph/StudioModal.tsx
- eventcatalog/src/utils/node-graphs/export-node-graph.ts
Added ability to take any visualizer from EventCatalog and open it in studio for designs.
> feat(core): added ability to open visualizer into studio

- .changeset/dull-rocks-give.md
- eventcatalog/src/pages/docs/[type]/[id]/[version]/asyncapi/[filename].astro
- eventcatalog/src/pages/docs/[type]/[id]/[version]/asyncapi/_[filename].data.ts
- eventcatalog/src/pages/docs/[type]/[id]/[version]/graphql/[filename].astro
- eventcatalog/src/pages/docs/[type]/[id]/[version]/graphql/_[filename].data.ts
- eventcatalog/src/pages/docs/[type]/[id]/[version]/spec/[filename].astro
- eventcatalog/src/pages/docs/[type]/[id]/[version]/spec/_[filename].data.ts
Added support for remote specification files.
The build server will need access to the URL of the specification file
> feat(core): added support for remote spec files
